$_PACKAGE := core.kernel.thread.sched

$_MODS += core

$_DEPS-core += $(CONFIG_SCHED_STRATEGY)
$_DEPS-core += core.kernel.timer
$_DEPS-core += embox.hal.context
$_DEPS-core += core.kernel.thread.thread

$_SRCS-core += sched.c
