$_PACKAGE := core.kernel.critical

$_LIBS     += libcritical.a
$_SRCS-libcritical.a += count.c

$_REQUIRES-libcritical.a += core.kernel.softirq_api
$_REQUIRES-libcritical.a += core.kernel.irq_api
$_REQUIRES-libcritical.a += core.kernel.sched_api
