$_PACKAGE := core.kernel.critical

$_MODS      += core
$_SRCS-core += count.c

$_REQUIRES-core += core.kernel.softirq_api
$_REQUIRES-core += core.kernel.irq_api
$_REQUIRES-core += core.kernel.sched_api
