$_PACKAGE = embox.test.kernel.thread.sched_policy

$_MODS                    += priority_based_test
$_SRCS-priority_based_test = priority_based_test.c
$_DEPS-priority_based_test = core.kernel.thread.sched_policy.priority_based
