$_MODS += wake_up_test
$_SRCS-wake_up_test += wake_up.c
$_DEPS-wake_up_test += $(PLATFORM).driver.nxt_motor
$_DEPS-wake_up_test += $(PLATFORM).driver.nxt_avr_init
$_DEPS-wake_up_test += $(PLATFORM).driver.soft_i2c
$_DEPS-wake_up_test += embox.driver.pins
