$_PACKAGE = embox.example.util

$_MODS += readline
$_SRCS-readline 	+= readline.c

$_MODS += circular_buffer
$_SRCS-circular_buffer	+= circular_buffer.c

$_MODS += tree_set
$_SRCS-tree_set += tree_set.c
