proc __expect_regexp {pattern} {
	expect {
	     timeout { puts "\n\nautotest error: Waiting for \"$pattern\" pattern timeout\n\n"; exit 1 }
		-re "$pattern" {}
	}
	return 0
}

# Sends $cmd to remote target (Embox) and sequentially waits for each
# pattern from $args to appear
proc test_assert_regexp_equal {args} {
	foreach pattern $args {
		__expect_regexp $pattern
	}
	return 0
}

proc test_assert_regexp_equal_timeout {new_timeout args} {
	set timeout $new_timeout

	foreach pattern $args {
		__expect_regexp $pattern
	}

	set timeout 10
	return 0
}
