proc ::autotest::telnet_connect {} {
	# https://stackoverflow.com/questions/30532532/expect-fails-when-running-proc-inside-proc
	global spawn_id
	variable embox_ip

	spawn telnet $embox_ip

	# The piece of embox's prompt
	set TELNET_PROMPT ":/#"
	expect {
		timeout { puts "\ntelnet: connection timeout\n"; exit 1 }
		-re "$TELNET_PROMPT" { }
	}
	return 0
}

proc ::autotest::telnet_disconnect {} {
	send "exit\r"
	expect "Connection closed by foreign host"
	return 0
}

proc ::autotest::test_exec {mode test_name test_body} {
	# https://stackoverflow.com/questions/30532532/expect-fails-when-running-proc-inside-proc
	global spawn_id

	if {$test_body == ""} {
		return 0
	}

	if {$mode == "target"} { telnet_connect }

	set res [eval $test_body]
	if {$res != 0} {
		if {$mode == "target"} { telnet_disconnect }
		return -1
	}

	if {$mode == "target"} { telnet_disconnect }

	return 0
}
