$_MODS += box_around_cmd

$_SRCS-box_around_cmd += box_around.c

$_DEPS-box_around_cmd += $(PLATFORM).driver.sonar_sensor
$_DEPS-box_around_cmd += $(PLATFORM).driver.nxt_motor
$_DEPS-box_around_cmd += $(PLATFORM).driver.nxt_avr_init
