

$_PACKAGE := embox.pnet.core.pack

$_APIS += api

$_MODS += pack_skbuf
$_SRCS-pack_skbuf += pack_skbuf/*.[ch]
$_DEPS-pack_skbuf += embox.net.core
$_PROVIDES-pack_skbuf += api

$_MODS += pack_standalone
$_SRCS-pack_standalone += pack_standalone/*.[ch]
$_PROVIDES-pack_standalone += api

