$_PACKAGE = embox.test.kernel.thread

$_MODS           += state_test
$_SRCS-state_test = state_test.c
$_DEPS-state_test = core.kernel.thread.state

$_MODS           += sched_test
$_SRCS-sched_test = sched_test.c
$_DEPS-sched_test = core.kernel.thread.sched

$_MODS           += core_test
$_SRCS-sched_test = core_test.c
$_DEPS-sched_test = core.kernel.thread.core
