
$_MODS += touch_test sensor_test

$_SRCS-touch_test += touch.c
$_DEPS-touch_test += $(PLATFORM).driver.touch_sensor

$_SRCS-sensor_test += sensor.c
$_DEPS-sensor_test += $(PLATFORM).driver.nxt_avr_init embox.driver.pins
