$_APIS += objalloc

$_MODS                 += pool_adapter
$_SRCS-pool_adapter      += pool_adapter.c
$_PROVIDES-pool_adapter  += objalloc

$_MODS                 += cache_adapter
$_SRCS-cache_adapter      += cache_adapter.c
$_PROVIDES-cache_adapter  += objalloc
