
$_MODS += irq_nesting irq_force irq_deep_handler

$_SRCS-irq_nesting += *irq_nesting.c
$_SRCS-irq_force += *irq_force.c
$_SRCS-irq_deep_handler += *irq_deep_handler.c

$_DEPS-irq_deep_handler += recursion
