include $(SCRIPTS_DIR)/autoconf

SUBDIRS-y   += ipv4
SUBDIRS-y   += ethernet
SUBDIRS-y   += core

OBJS-y      += socket.o
#OBJS-y      += sockets.o
OBJS-y      += ipconfig.o
OBJS-y      += ipaux.o

include $(SRC_DIR)/common.mk
