#!/bin/bash

on_sig() {
	intr=1
	$EMBOX_DIR/scripts/docker/docker_run.sh killgdbwrapper $1
}

for i in 1 2 3 9 14 15; do
	trap "on_sig $i;" $i
done

EMBOX_DIR=$(dirname $(readlink -f $0))/../..

$EMBOX_DIR/scripts/docker/docker_run.sh \
	PROJECT_LOC=$EMBOX_DIR \
	gdbwrapper2 \
	<&0 "$@" &
PID=$!

intr=1
while [ $intr ]; do
	intr=
	wait $PID
	EXIT_STATUS=$?
done

exit $EXIT_STATUS

