
$_SUBDIRS := $(ARCH)

$_PACKAGE := embox.hal

$_CPPFLAGS += -D__HAL__

# Each HAL implementation should provide the following mods definition.
# Kernel assumes their presense.
$_MODS += arch clock interrupt traps
