
$_MODS += esh
$_SRCS-esh += esh.c #../shell/shell_command.c
#$_DEPS-esh += core.kernel.printk #core.kernel.job embox.hal.context
$_DEPS-esh += core.kernel.job embox.hal.context
$_DEPS-esh += shell_command

#$_CPPFLAGS-shell += -I$(AUTOCONF_DIR)
#$($_SELFDIR)/esh.c : $(AUTOCONF_DIR)/start_script.inc


