/*
 * lspnp_help.inc
 *
 * Created on: 20.02.2009
 *      Author: abatyukov
 */
"*** LSPNP\n"
" - show list of plan and play devices\n"
"*FORMAT: lspnp [-b <bus_type> [-n <dev_id>]]\n"
"\t <bus_type> - type of the bus of plag and play device.\n"
"\t              Possible values: ahbm - AHB bus, master\n"
"\t                               ahbsl - AHB bus, slave\n"
"\t                               apb - APB bus\n"
"\t                               all - AHB&APB buses\n"
"\t              by default: all\n"
"\t <dev_id>   - number of required device."
