$_PACKAGE := embox.example.kernel.x86debugTraps

$_MODS                   += x86debugTraps
$_SRCS-x86debugTraps            += x86debugTraps.c
$_DEPS-x86debugTraps            += embox.kernel.thread.core

$_BRIEF-x86debugTraps = demonstrates using x86 int01 and int03
