$_PACKAGE := embox.example.kernel.x86debugTraps

$_MODS                   += x86debugTraps
$_SRCS-thread            += x86debugTraps.c
$_DEPS-thread            += embox.kernel.thread.core

$_BRIEF-thread = demonstrates using thread API
