
$_MODS += soft_traps
$_MODS += soft_traps_data
$_MODS += soft_traps_flags

$_SRCS-soft_traps       += soft_traps.c
$_SRCS-soft_traps_data  += soft_traps_data.c
$_SRCS-soft_traps_flags += soft_traps_flags.c

$_DEPS-soft_traps += embox.hal.test.traps
$_DEPS-soft_traps += embox.hal.traps

$_DEPS-soft_traps_data += embox.hal.test.traps
$_DEPS-soft_traps_data += embox.hal.traps

$_DEPS-soft_traps_flags += embox.hal.test.traps
$_DEPS-soft_traps_flags += embox.hal.traps

