$_MODS += bluetooth_test
$_SRCS-bluetooth_test += bluetooth.c
$_DEPS-bluetooth_test += $(PLATFORM).driver.nxt_bluetooth
$_DEPS-bluetooth_test += $(PLATFORM).driver.nxt_avr_init
$_DEPS-bluetooth_test += embox.driver.pins
