
$_CPPFLAGS += -I$($PLATFORM)/include
$_MODS += bluetooth_test
$_SRCS-bluetooth_test += bluetooth.c
$_DEPS-bluetooth_test += $(PLATFORM).driver.nxt_bluetooth $(PLATFORM).driver.nxt_avr_init $(PLATFORM).driver.soft_i2c embox.driver.pins
