$_PACKAGE := embox.compat

$_MODS += posix

$_SRCS-posix += exec.c
$_SRCS-posix += file.c
$_SRCS-posix += fork.c
$_SRCS-posix += getopt.c
$_SRCS-posix += select.c
$_SRCS-posix += utsname.c
$_SRCS-posix += wait.c

$_CPPFLAGS += -I$(SRC_DIR)/compat/posix/include
