####################################################
# Posix TTY Device Module
####################################################
$_PACKAGE := embox.driver

$_MODS += tty_posix

$_SRCS-tty_posix += keyboard.c
$_SRCS-tty_posix += console.c
#$_SRCS-tty_posix += pty.c
#$_SRCS-tty_posix += rs232.c
$_SRCS-tty_posix += tty.c

$_BRIEF-tty_posix = TTY posix implementation
