OBJS-y     += string.o strchr.o strrchr.o strcmp.o strcat.o strerror.o memccpy.o memcpy.o strstr.o strncmp.o strcpy.o strncpy.o memchr.o memcmp.o memmove.o bcopy.o memset.o strcoll.o strspn.o strcspn.o strlen.o strncat.o strpbrk.o basename.o strtok.o

include $(SCRIPTS_DIR)/common.mk
