SUBDIRS:=

OBJS:=mmu_asm.o test_save_restore_traps.o boot.o window_overflow_func.o restore_proc_context.o save_proc_context.o traps.o window_save.o window_restore.o bubble_sort.o

include $(SRC_DIR)/common.mk
