OBJS-y:= leon_irq.o \
         init.o \
         mmu_asm.o \
         boot.o \
         cpu_context.o \
         traps.o \
         windows.o \
         bubble_sort.o \
         sys.o \
         cpu_context_traps.o \
         srmmu_probe.o \
      	 soft_trap_test.o

include $(SRC_DIR)/common.mk
