
$_CPPFLAGS += -I$($PLATFORM)/include
$_MODS += without_sensors pen_ligth

$_SRCS-without_sensors += without_sensors.c
$_DEPS-without_sensors += $(PLATFORM).driver.nxt_motor

$_SRCS-pen_ligth += pen_ligth.c
$_DEPS-pen_ligth += $(PLATFORM).driver.nxt_motor
