$_PACKAGE:= embox.example.framework

$_MODS                   += array_registry
$_SRCS-array_registry    += array_registry.c

$_BRIEF-array_registry = demonstrates create object repository with ARRAY_SPREAD API
