#!/bin/bash
ip=$(which ip)

$ip link add name br0 type bridge
$ip link set dev br0 up
$ip addr flush dev br0
$ip link set dev br0 address aa:bb:cc:dd:ee:00
$ip addr add dev br0 10.0.2.1/24

DATADIR=$(dirname "$0")

sudo -E qemu-system-i386 -kernel ./build/base/bin/embox -enable-kvm -m 256 -nographic \
-netdev tap,id=n0,ifname="tap0",script=$DATADIR/start_script,downscript=$DATADIR/stop_script,vnet_hdr=no \
-device virtio-net-pci,netdev=n0,mac=52:54:CC:DD:EE:00

$ip link delete br0 type bridge
