#!/bin/bash

echo -ne "HTTP/1.1 200 OK\r\n"
echo -ne "Content-Type: text/event-stream\r\n"
echo -ne "Cache-Control: no-cache\r\n"
echo -ne "Connection: keep-alive\r\n"
echo -ne "\r\n"

while true; do
	i=$((1 + $RANDOM % 15000))
	echo -ne "data: {\"light\" : \"$i\"}\n\n" 2>/dev/null || exit 0
	sleep 1
done
