#ifndef PNP_H_
#define PNP_H_

#define VENDOR_ID_GAISLER				0x01

#define DEV_ID_GAISLER_LEON3_CPU		0x003
#define DEV_ID_GAISLER_JTAG 			0x01C
#define DEV_ID_GAISLER_DDR2_CTRLR		0x02E
#define DEV_ID_GAISLER_AHB_ABP_BRIDGE	0x006
#define DEV_ID_GAISLER_LEON3_DSU		0x004
#define DEV_ID_GAISLER_TIMER 			0x011
#define DEV_ID_GAISLER_INTERRUPT_UNIT 	0x00D



#define VENDOR_ID_ESA					0x04

#define DEV_ID_ESA_LEON2_MEM_CTRLR		0x00F

#endif
