/**
 * @file
 * @brief ISM43362-M3G-L44-SPI Inventek eS-WiFi module library
 * @author Daria Pechenova
 * @version
 * @date 18.07.2025
 */

#ifndef ISM43362_CONFIG_H_
#define ISM43362_CONFIG_H_

#include <config/board_config.h>

#define WIFI_SPI_BUS OPTION_GET(NUMBER, wifi_spi_bus)

#define CONF_SPI_PIN_CS_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_CS_PORT)
#define CONF_SPI_PIN_SCK_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS),_PIN_SCK_PORT)
#define CONF_SPI_PIN_MISO_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MISO_PORT)
#define CONF_SPI_PIN_MOSI_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MOSI_PORT)

#define CONF_SPI_PIN_CS_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_CS_NR))
#define CONF_SPI_PIN_SCK_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_SCK_NR))
#define CONF_SPI_PIN_MISO_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MISO_NR))
#define CONF_SPI_PIN_MOSI_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MOSI_NR))

#define CONF_SPI_PIN_SCK_AF \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_SCK_AF)
#define CONF_SPI_PIN_MISO_AF \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MISO_AF)
#define CONF_SPI_PIN_MOSI_AF \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_MOSI_AF)

#define CONF_SPI_PIN_WAKE_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_WAKE_PORT)
#define CONF_SPI_PIN_CMDDATA_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS),_PIN_CMDDATA_PORT)
#define CONF_SPI_PIN_RESET_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_RESET_PORT)
#define CONF_SPI_PIN_WIFI_LED_PORT \
            MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_WIFI_LED_PORT)

#define CONF_SPI_PIN_WAKE_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_WAKE_NR))
#define CONF_SPI_PIN_CMDDATA_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS),_PIN_CMDDATA_NR))
#define CONF_SPI_PIN_RESET_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_RESET_NR))
#define CONF_SPI_PIN_WIFI_LED_NR \
            (1 << MACRO_CONCAT(MACRO_CONCAT(CONF_SPI, WIFI_SPI_BUS), _PIN_WIFI_LED_NR))

#endif /* ISM43362_CONFIG_H_ */