include $(SCRIPTS_DIR)/autoconf

SUBDIRS-$(MONITOR_USER_ARP)       += arp
SUBDIRS-$(MONITOR_USER_GOTO)      += goto
SUBDIRS-y      += help
SUBDIRS-$(MONITOR_USER_LDIMG)     += ldimg
SUBDIRS-$(MONITOR_USER_PNPLS)     += lspnp
SUBDIRS-$(MONITOR_USER_MEM)       += mem
SUBDIRS-$(MONITOR_USER_MMU_PROBE) += mmu_probe
SUBDIRS-$(MONITOR_USER_PING)      += ping
SUBDIRS-$(MONITOR_USER_UDPD)      += udpd
SUBDIRS-$(MONITOR_USER_WMEM)      += wmem
SUBDIRS-$(MONITOR_USER_LS)        += ls

include $(SRC_DIR)/common.mk
