include $(SCRIPTS_DIR)/autoconf

SUBDIRS-$(MONITOR_USER_ARP)      += arp
SUBDIRS-$(MONITOR_USER_HELP)     += help
SUBDIRS-$(MONITOR_USER_LSPNP)    += lspnp
SUBDIRS-$(MONITOR_USER_MEM)      += mem
SUBDIRS-$(MONITOR_USER_MMU_PROBE)+= mmu_probe
SUBDIRS-$(MONITOR_USER_PING)     += ping
SUBDIRS-$(MONITOR_USER_RUN)      += run
SUBDIRS-$(MONITOR_USER_UDPD)     += udpd
SUBDIRS-$(MONITOR_USER_WMEM)     += wmem

include $(SRC_DIR)/common.mk
