include $(SCRIPTS_DIR)/autoconf

SUBDIRS-y += shell
SUBDIRS-y += arp
SUBDIRS-y += cp
SUBDIRS-y += goto
SUBDIRS-y += help
SUBDIRS-y += ldimg
SUBDIRS-y += lspnp
SUBDIRS-y += man
SUBDIRS-y += mem
SUBDIRS-y += mmu_probe
SUBDIRS-y += ping
SUBDIRS-y += ls
SUBDIRS-y += testmem
SUBDIRS-y += udpd
SUBDIRS-y += wmem
SUBDIRS-y += tftp

include $(SCRIPTS_DIR)/common.mk
