
$_PACKAGE := $(PLATFORM).pnet.node.direct_comm

$_MODS += executer
$_DEPS-executer += $(PLATFORM).driver.nxt_motor
$_SRCS-executer += executer.c

$_MODS += executer_embox
$_DEPS-executer_embox += $(PLATFORM).driver.nxt_motor
$_SRCS-executer_embox += executer_embox.c

$_MODS += formation
$_SRCS-formation += formation.c
