
$_MODS += help

$_SRCS-help += *.c
$_DEPS-help += shell_command

$_BRIEF-help = Shows all available commands

define $_DETAILS-help
NAME
	help - displays all possible commands
SYNOPSIS
	help
AUTHORS
	Alexandr Batyukov
endef
