$_PACKAGE := embox.test.kernel.task

$_MODS += task
$_SRCS-task += task.c
$_DEPS-task += embox.fs.core embox.fs.rootfs embox.kernel.thread.sched embox.kernel.thread.core embox.driver.serial.apbuart
$_REQUIRES-task += embox.kernel.tasks_api

$_BRIEF-task = new taks IO managment example

