# Generated by Xpand using M2Make template.

# Factory for 'EModel' model.

ifndef __model_factory_mk
__model_factory_mk := $(lastword $(MAKEFILE_LIST))

# Provides methods for creating objects of 'EModel' model.
# See 'eModelFactory'.
define class-EModelFactory
	$(super EFactory)

	# Creates a new 'ENode' model object.
	$(method createENode)

	# Creates a new 'ELink' model object.
	$(method createELink)

	# Creates a new 'EMetaClass' model object.
	$(method createEMetaClass)

	# Creates a new 'EMetaPrimitive' model object.
	$(method createEMetaPrimitive)

	# Creates a new 'EMetaReference' model object.
	$(method createEMetaReference)

	# Creates a new 'EMetaAttribute' model object.
	$(method createEMetaAttribute)

	# Creates a new 'EMetaModel' model object.
	$(method createEMetaModel)

	# Creates a new 'EFactory' model object.
	$(method createEFactory)
endef

$(def_all)

include $(dir $(__model_factory_mk))factory_impl.mk

eModelFactory := $(call new,EModelFactoryImpl)

endif # __model_factory_mk

