# Generated by Xpand using M2Make template.

# Implementation of factory for 'EModel' model.

ifndef __model_factory_mk
$(error \
	Do not include this file directly, include 'factory.mk' instead!)
endif # __model_factory_mk

# Implements methods for creating objects of 'EModel' model.
define class-EModelFactoryImpl
	$(super EModelFactory)

	$(super EFactoryImpl)

	$(method createENode,
		$(new ENodeImpl))

	$(method createELink,
		$(new ELinkImpl))

	$(method createEMetaClass,
		$(new EMetaClassImpl))

	$(method createEMetaPrimitive,
		$(new EMetaPrimitiveImpl))

	$(method createEMetaReference,
		$(new EMetaReferenceImpl))

	$(method createEMetaAttribute,
		$(new EMetaAttributeImpl))

	$(method createEMetaModel,
		$(new EMetaModelImpl))

	$(method createEFactory,
		$(new EFactoryImpl))
endef

$(def_all)

