# Generated by Xpand using M2Make template.

# Factory for 'EModel' model.

ifndef __model_factory_mk
__model_factory_mk := $(lastword $(MAKEFILE_LIST))

# Provides methods for creating objects of 'EModel' model.
# See 'eModelFactory'.
define class-EModelFactory

	# Creates a new 'EObject' model object.
	$(method createEObject,
		$(new EObjectImpl))

	# Creates a new 'ELink' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createELink,
		$(for e <- $(new ELinkImpl),$(set e->name,$(value 1))$e))

	# Creates a new 'EMetaClass' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createEMetaClass,
		$(for e <- $(new EMetaClassImpl),$(set e->name,$(value 1))$e))

	# Creates a new 'EMetaPrimitive' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createEMetaPrimitive,
		$(for e <- $(new EMetaPrimitiveImpl),$(set e->name,$(value 1))$e))

	# Creates a new 'EMetaReference' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createEMetaReference,
		$(for e <- $(new EMetaReferenceImpl),$(set e->name,$(value 1))$e))

	# Creates a new 'EMetaAttribute' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createEMetaAttribute,
		$(for e <- $(new EMetaAttributeImpl),$(set e->name,$(value 1))$e))

	# Creates a new 'EMetaModel' model object.
	#   1. (optional) initial value of 'name' property.
	$(method createEMetaModel,
		$(for e <- $(new EMetaModelImpl),$(set e->name,$(value 1))$e))
endef

$(def_all)

eModelFactory := $(call new,EModelFactory)

endif # __model_factory_mk

