# Generated by Xpand using M2Make template.

# Metamodel implementation for 'EModel' package.

ifndef __model_metamodel_impl_mk
__model_metamodel_impl_mk := $(lastword $(MAKEFILE_LIST))

# Creates and initializes contents of 'EModel' meta model.
define class-EModelMetaModelImpl
	$(super EModelMetaModel)

	$(super EMetaModelImpl)

	# Define properties as fields.

	$(property-field ENode,
		$(invoke createMetaClass,ENode))
	$(property-field ENode_eMetaClass,
		$(invoke createMetaReference,$(get ENode),ENode_eMetaClass))
	$(property-field ENode_eResource,
		$(invoke createMetaAttribute,$(get ENode),ENode_eResource))
	$(property-field ENode_eContainer,
		$(invoke createMetaReference,$(get ENode),ENode_eContainer))
	$(property-field ENode_eRootContainer,
		$(invoke createMetaReference,$(get ENode),ENode_eRootContainer))
	$(property-field ENode_eContents,
		$(invoke createMetaReference,$(get ENode),ENode_eContents))
	$(property-field ENode_eAllContents,
		$(invoke createMetaReference,$(get ENode),ENode_eAllContents))

	$(property-field ELink,
		$(invoke createMetaClass,ELink))
	$(property-field ELink_eMetaReference,
		$(invoke createMetaReference,$(get ELink),ELink_eMetaReference))

	$(property-field EMetaType,
		$(invoke createMetaClass,EMetaType))
	$(property-field EMetaType_instanceClass,
		$(invoke createMetaAttribute,$(get EMetaType),EMetaType_instanceClass))
	$(property-field EMetaType_eMetaModel,
		$(invoke createMetaReference,$(get EMetaType),EMetaType_eMetaModel))

	$(property-field EMetaClass,
		$(invoke createMetaClass,EMetaClass))
	$(property-field EMetaClass_abstract,
		$(invoke createMetaAttribute,$(get EMetaClass),EMetaClass_abstract))
	$(property-field EMetaClass_interface,
		$(invoke createMetaAttribute,$(get EMetaClass),EMetaClass_interface))
	$(property-field EMetaClass_eSuperTypes,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eSuperTypes))
	$(property-field EMetaClass_eAllSuperTypes,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAllSuperTypes))
	$(property-field EMetaClass_eFeatures,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eFeatures))
	$(property-field EMetaClass_eAllFeatures,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAllFeatures))
	$(property-field EMetaClass_eAttributes,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAttributes))
	$(property-field EMetaClass_eAllAttributes,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAllAttributes))
	$(property-field EMetaClass_eReferences,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eReferences))
	$(property-field EMetaClass_eAllReferences,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAllReferences))
	$(property-field EMetaClass_eAllContainments,
		$(invoke createMetaReference,$(get EMetaClass),EMetaClass_eAllContainments))

	$(property-field EMetaPrimitive,
		$(invoke createMetaClass,EMetaPrimitive))

	$(property-field EMetaFeature,
		$(invoke createMetaClass,EMetaFeature))
	$(property-field EMetaFeature_changeable,
		$(invoke createMetaAttribute,$(get EMetaFeature),EMetaFeature_changeable))
	$(property-field EMetaFeature_volatile,
		$(invoke createMetaAttribute,$(get EMetaFeature),EMetaFeature_volatile))
	$(property-field EMetaFeature_transient,
		$(invoke createMetaAttribute,$(get EMetaFeature),EMetaFeature_transient))
	$(property-field EMetaFeature_derived,
		$(invoke createMetaAttribute,$(get EMetaFeature),EMetaFeature_derived))
	$(property-field EMetaFeature_instanceProperty,
		$(invoke createMetaAttribute,$(get EMetaFeature),EMetaFeature_instanceProperty))
	$(property-field EMetaFeature_eContainingClass,
		$(invoke createMetaReference,$(get EMetaFeature),EMetaFeature_eContainingClass))

	$(property-field EMetaReference,
		$(invoke createMetaClass,EMetaReference))
	$(property-field EMetaReference_containment,
		$(invoke createMetaAttribute,$(get EMetaReference),EMetaReference_containment))
	$(property-field EMetaReference_container,
		$(invoke createMetaAttribute,$(get EMetaReference),EMetaReference_container))
	$(property-field EMetaReference_eOpposite,
		$(invoke createMetaReference,$(get EMetaReference),EMetaReference_eOpposite))
	$(property-field EMetaReference_eReferenceType,
		$(invoke createMetaReference,$(get EMetaReference),EMetaReference_eReferenceType))

	$(property-field EMetaAttribute,
		$(invoke createMetaClass,EMetaAttribute))
	$(property-field EMetaAttribute_eAttributeType,
		$(invoke createMetaReference,$(get EMetaAttribute),EMetaAttribute_eAttributeType))

	$(property-field EMetaModel,
		$(invoke createMetaClass,EMetaModel))
	$(property-field EMetaModel_eFactory,
		$(invoke createMetaReference,$(get EMetaModel),EMetaModel_eFactory))
	$(property-field EMetaModel_eTypes,
		$(invoke createMetaReference,$(get EMetaModel),EMetaModel_eTypes))

	$(property-field EModelFactory,
		$(invoke createMetaClass,EModelFactory))
	$(property-field EModelFactory_eMetaModel,
		$(invoke createMetaReference,$(get EModelFactory),EModelFactory_eMetaModel))

	$(property-field ENamed,
		$(invoke createMetaClass,ENamed))
	$(property-field ENamed_name,
		$(invoke createMetaAttribute,$(get ENamed),ENamed_name))

	$(property-field ETyped,
		$(invoke createMetaClass,ETyped))
	$(property-field ETyped_lowerBound,
		$(invoke createMetaAttribute,$(get ETyped),ETyped_lowerBound))
	$(property-field ETyped_upperBound,
		$(invoke createMetaAttribute,$(get ETyped),ETyped_upperBound))
	$(property-field ETyped_eType,
		$(invoke createMetaReference,$(get ETyped),ETyped_eType))

	# Initialize the objects and relations between them.

	$(invoke initMetaClass,$(get ENode),
		ENode,,)
	$(invoke initMetaReference,$(get ENode_eMetaClass),
		eMetaClass,0,1,$(get EMetaClass),,volatile derived transient)
	$(invoke initMetaAttribute,$(get ENode_eResource),
		eResource,0,1,volatile derived transient)
	$(invoke initMetaReference,$(get ENode_eContainer),
		eContainer,0,1,$(get ENode),,volatile derived transient)
	$(invoke initMetaReference,$(get ENode_eRootContainer),
		eRootContainer,0,1,$(get ENode),,volatile derived transient)
	$(invoke initMetaReference,$(get ENode_eContents),
		eContents,0,,$(get ENode),$(get ENode_eContents),volatile derived transient)
	$(invoke initMetaReference,$(get ENode_eAllContents),
		eAllContents,0,,$(get ENode),$(get ENode_eAllContents),volatile derived transient)

	$(invoke initMetaClass,$(get ELink),
		ELink,$(get ENamed),)
	$(invoke initMetaReference,$(get ELink_eMetaReference),
		eMetaReference,0,1,$(get EMetaReference),,changeable)

	$(invoke initMetaClass,$(get EMetaType),
		EMetaType,$(get ENamed),abstract)
	$(invoke initMetaAttribute,$(get EMetaType_instanceClass),
		instanceClass,0,1,changeable)
	$(invoke initMetaReference,$(get EMetaType_eMetaModel),
		eMetaModel,0,1,$(get EMetaModel),$(get EMetaModel_eTypes),transient container)

	$(invoke initMetaClass,$(get EMetaClass),
		EMetaClass,$(get EMetaType),)
	$(invoke initMetaAttribute,$(get EMetaClass_abstract),
		abstract,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaClass_interface),
		interface,0,1,changeable)
	$(invoke initMetaReference,$(get EMetaClass_eSuperTypes),
		eSuperTypes,0,,$(get EMetaClass),,changeable)
	$(invoke initMetaReference,$(get EMetaClass_eAllSuperTypes),
		eAllSuperTypes,0,,$(get EMetaClass),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eFeatures),
		eFeatures,0,,$(get EMetaFeature),$(get EMetaFeature_eContainingClass),changeable containment)
	$(invoke initMetaReference,$(get EMetaClass_eAllFeatures),
		eAllFeatures,0,,$(get EMetaFeature),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eAttributes),
		eAttributes,0,,$(get EMetaAttribute),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eAllAttributes),
		eAllAttributes,0,,$(get EMetaAttribute),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eReferences),
		eReferences,0,,$(get EMetaReference),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eAllReferences),
		eAllReferences,0,,$(get EMetaReference),,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaClass_eAllContainments),
		eAllContainments,0,,$(get EMetaReference),,volatile derived transient)

	$(invoke initMetaClass,$(get EMetaPrimitive),
		EMetaPrimitive,$(get EMetaType),)

	$(invoke initMetaClass,$(get EMetaFeature),
		EMetaFeature,$(get ETyped),abstract)
	$(invoke initMetaAttribute,$(get EMetaFeature_changeable),
		changeable,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaFeature_volatile),
		volatile,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaFeature_transient),
		transient,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaFeature_derived),
		derived,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaFeature_instanceProperty),
		instanceProperty,0,1,changeable)
	$(invoke initMetaReference,$(get EMetaFeature_eContainingClass),
		eContainingClass,0,1,$(get EMetaClass),$(get EMetaClass_eFeatures),transient container)

	$(invoke initMetaClass,$(get EMetaReference),
		EMetaReference,$(get EMetaFeature),)
	$(invoke initMetaAttribute,$(get EMetaReference_containment),
		containment,0,1,changeable)
	$(invoke initMetaAttribute,$(get EMetaReference_container),
		container,0,1,volatile derived transient)
	$(invoke initMetaReference,$(get EMetaReference_eOpposite),
		eOpposite,0,1,$(get EMetaReference),,changeable)
	$(invoke initMetaReference,$(get EMetaReference_eReferenceType),
		eReferenceType,1,1,$(get EMetaClass),,volatile derived transient)

	$(invoke initMetaClass,$(get EMetaAttribute),
		EMetaAttribute,$(get EMetaFeature),)
	$(invoke initMetaReference,$(get EMetaAttribute_eAttributeType),
		eAttributeType,1,1,$(get EMetaPrimitive),,volatile derived transient)

	$(invoke initMetaClass,$(get EMetaModel),
		EMetaModel,$(get ENamed),)
	$(invoke initMetaReference,$(get EMetaModel_eFactory),
		eFactory,1,1,$(get EModelFactory),$(get EModelFactory_eMetaModel),changeable transient)
	$(invoke initMetaReference,$(get EMetaModel_eTypes),
		eTypes,0,,$(get EMetaType),$(get EMetaType_eMetaModel),changeable containment)

	$(invoke initMetaClass,$(get EModelFactory),
		EModelFactory,,)
	$(invoke initMetaReference,$(get EModelFactory_eMetaModel),
		eMetaModel,1,1,$(get EMetaModel),$(get EMetaModel_eFactory),changeable transient)

	$(invoke initMetaClass,$(get ENamed),
		ENamed,,abstract)
	$(invoke initMetaAttribute,$(get ENamed_name),
		name,0,1,changeable)

	$(invoke initMetaClass,$(get ETyped),
		ETyped,$(get ENamed),abstract)
	$(invoke initMetaAttribute,$(get ETyped_lowerBound),
		lowerBound,0,1,changeable)
	$(invoke initMetaAttribute,$(get ETyped_upperBound),
		upperBound,0,1,changeable)
	$(invoke initMetaReference,$(get ETyped_eType),
		eType,0,1,$(get EMetaType),,changeable)

	# Bind objects to instance classes and features to properties.

	$(invoke bindMetaClass,$(get ENode),ENode)
	$(invoke bindMetaFeature,$(get ENode_eMetaClass),eMetaClass)
	$(invoke bindMetaFeature,$(get ENode_eResource),eResource)
	$(invoke bindMetaFeature,$(get ENode_eContainer),eContainer)
	$(invoke bindMetaFeature,$(get ENode_eRootContainer),eRootContainer)
	$(invoke bindMetaFeature,$(get ENode_eContents),eContents)
	$(invoke bindMetaFeature,$(get ENode_eAllContents),eAllContents)

	$(invoke bindMetaClass,$(get ELink),ELink)
	$(invoke bindMetaFeature,$(get ELink_eMetaReference),eMetaReference)

	$(invoke bindMetaClass,$(get EMetaType),EMetaType)
	$(invoke bindMetaFeature,$(get EMetaType_instanceClass),instanceClass)
	$(invoke bindMetaFeature,$(get EMetaType_eMetaModel),eMetaModel)

	$(invoke bindMetaClass,$(get EMetaClass),EMetaClass)
	$(invoke bindMetaFeature,$(get EMetaClass_abstract),isAbstract)
	$(invoke bindMetaFeature,$(get EMetaClass_interface),isInterface)
	$(invoke bindMetaFeature,$(get EMetaClass_eSuperTypes),eSuperTypes)
	$(invoke bindMetaFeature,$(get EMetaClass_eAllSuperTypes),eAllSuperTypes)
	$(invoke bindMetaFeature,$(get EMetaClass_eFeatures),eFeatures)
	$(invoke bindMetaFeature,$(get EMetaClass_eAllFeatures),eAllFeatures)
	$(invoke bindMetaFeature,$(get EMetaClass_eAttributes),eAttributes)
	$(invoke bindMetaFeature,$(get EMetaClass_eAllAttributes),eAllAttributes)
	$(invoke bindMetaFeature,$(get EMetaClass_eReferences),eReferences)
	$(invoke bindMetaFeature,$(get EMetaClass_eAllReferences),eAllReferences)
	$(invoke bindMetaFeature,$(get EMetaClass_eAllContainments),eAllContainments)

	$(invoke bindMetaClass,$(get EMetaPrimitive),EMetaPrimitive)

	$(invoke bindMetaClass,$(get EMetaFeature),EMetaFeature)
	$(invoke bindMetaFeature,$(get EMetaFeature_changeable),isChangeable)
	$(invoke bindMetaFeature,$(get EMetaFeature_volatile),isVolatile)
	$(invoke bindMetaFeature,$(get EMetaFeature_transient),isTransient)
	$(invoke bindMetaFeature,$(get EMetaFeature_derived),isDerived)
	$(invoke bindMetaFeature,$(get EMetaFeature_instanceProperty),instanceProperty)
	$(invoke bindMetaFeature,$(get EMetaFeature_eContainingClass),eContainingClass)

	$(invoke bindMetaClass,$(get EMetaReference),EMetaReference)
	$(invoke bindMetaFeature,$(get EMetaReference_containment),isContainment)
	$(invoke bindMetaFeature,$(get EMetaReference_container),isContainer)
	$(invoke bindMetaFeature,$(get EMetaReference_eOpposite),eOpposite)
	$(invoke bindMetaFeature,$(get EMetaReference_eReferenceType),eReferenceType)

	$(invoke bindMetaClass,$(get EMetaAttribute),EMetaAttribute)
	$(invoke bindMetaFeature,$(get EMetaAttribute_eAttributeType),eAttributeType)

	$(invoke bindMetaClass,$(get EMetaModel),EMetaModel)
	$(invoke bindMetaFeature,$(get EMetaModel_eFactory),eFactory)
	$(invoke bindMetaFeature,$(get EMetaModel_eTypes),eTypes)

	$(invoke bindMetaClass,$(get EModelFactory),EModelFactory)
	$(invoke bindMetaFeature,$(get EModelFactory_eMetaModel),eMetaModel)

	$(invoke bindMetaClass,$(get ENamed),ENamed)
	$(invoke bindMetaFeature,$(get ENamed_name),name)

	$(invoke bindMetaClass,$(get ETyped),ETyped)
	$(invoke bindMetaFeature,$(get ETyped_lowerBound),lowerBound)
	$(invoke bindMetaFeature,$(get ETyped_upperBound),upperBound)
	$(invoke bindMetaFeature,$(get ETyped_eType),eType)

endef

$(def_all)

endif # __model_metamodel_impl_mk

