
#FIXME use OR or other!
ifdef CONFIG_PP_ENABLE
ifdef CONFIG_PP_TEST

$_MODS += pp_test

$_DEPS-pp_test += core.kernel.pp
$_DEPS-pp_test += core.kernel.thread.core

$_SRCS-pp_test += pp_test.c

endif
endif

