$_PACKAGE = embox.test.tty

$_MODS           += kbd_test
$_SRCS-kbd_test = kbd.c
$_DEPS-kbd_test += embox.driver.tty_posix

#$_MODS           += screen_test
#$_SRCS-screen_test = screen.c
#$_DEPS-screen_test += embox.driver.screen
