$_APIS += objalloc

$_MODS                   += pool_adapter
$_SRCS-pool_adapter      += pool_adapter.c
$_PROVIDES-pool_adapter  += objalloc
$_DEPS-pool_adapter += slab

$_MODS                 += slab_adapter
$_SRCS-slab_adapter      += slab_adapter.c
$_PROVIDES-slab_adapter  += objalloc
$_DEPS-slab_adapter += slab

