$_APIS += objalloc

$_MODS                   += pool_adapter
$_SRCS-pool_adapter      += pool_adapter.[c|h]
$_PROVIDES-pool_adapter  += objalloc

$_MODS                   += slab_adapter
$_SRCS-slab_adapter      += slab_adapter.[c|h]
$_DEPS-slab_adapter      += slab
$_PROVIDES-slab_adapter  += objalloc

