$_PACKAGE = embox.driver.virtual

$_MODS 					+= diag_device
$_SRCS-diag_device	  	+= diag_device.c
$_REQUIRES-diag_device	+= embox.hal.diag

$_MODS 					+= zero
$_SRCS-zero 			+= zero.c
$_DEPS-zero 			+= embox.fs.devfs

$_MODS 					+= null
$_SRCS-null 			+= null.c
$_DEPS-null 			+= embox.fs.devfs
