$_PACKAGE := embox.example.kernel.thread

$_MODS                   += thread
$_SRCS-thread            += thread.c
$_DEPS-thread            += core.kernel.thread.core

$_BRIEF-thread = demonstrates using thread API

