$_PACKAGE = embox.test.kernel.timer

$_MODS                += sleep_test
$_SRCS-sleep_test     += sleep_test.c
$_DEPS-sleep_test     += core.kernel.time
$_REQUIRES-sleep_test += core.kernel.timer.sleep_api

