$_PACKAGE := embox.example.kernel.task

$_MODS += task
$_SRCS-task += task.c
$_DEPS-task += embox.fs.core embox.fs.rootfs
$_DEPS-task += embox.kernel.thread.sched embox.kernel.thread.core
$_REQUIRES-task += embox.kernel.task_api

$_BRIEF-task = new tasks IO managment example
