/**
 * @file
 *
 * @date Aug 14, 2023
 * @author Anton Bondarev
 */

#ifndef SRC_DRIVERS_GPIO_STM32CUBE_STM32_GPIO_CONF_F2_H_
#define SRC_DRIVERS_GPIO_STM32CUBE_STM32_GPIO_CONF_F2_H_


#endif /* SRC_DRIVERS_GPIO_STM32CUBE_STM32_GPIO_CONF_F2_H_ */
