/**
 * @file
 *
 * @date 31.03.2020
 * @author Alexander Kalmuk
 */

#ifndef SRC_DRIVERS_GPIO_STM32_USART_STM32_USART_CONF_H7_H_
#define SRC_DRIVERS_GPIO_STM32_USART_STM32_USART_CONF_H7_H_


#endif /* SRC_DRIVERS_GPIO_STM32_USART_STM32_USART_CONF_H7_H_ */
