#!/bin/sh

echo -ne "HTTP/1.1 200 OK\r\n"
echo -ne "Content-Type: application/json\r\n"
echo -ne "Connection: close\r\n"
echo -ne "\r\n"

if [ $REQUEST_METHOD = "GET" ]; then
	echo "Query: $QUERY_STRING" >&2
	echo '[0, 1, 0, 1, 0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1,0, 1, 0, 1]'
elif [ $REQUEST_METHOD = "POST" ]; then
	read -n $CONTENT_LENGTH POST_DATA
	echo "Posted: $POST_DATA" >&2
fi
