$_PACKAGE:= embox.example.mem

$_MODS                   += objalloc
$_SRCS-objalloc          += objalloc.c
$_REQUIRES-objalloc      += embox.hal.mm.objalloc

$_BRIEF-objalloc = demonstrates using of API for allocation fixed size object
