/**
 * @file
 *
 * @author Andrey Kokorev
 */

#ifndef KERNEL_LTHREAD_PRIORITY_H_
#define KERNEL_LTHREAD_PRIORITY_H_

#include <kernel/sched/sched_priority.h>

#define LTHREAD_PRIORITY_MIN SCHED_PRIORITY_MAX - 255
#define LTHREAD_PRIORITY_MAX SCHED_PRIORITY_MAX

/** Total amount of valid priorities. */
#define LTHREAD_PRIORITY_TOTAL \
	(LTHREAD_PRIORITY_MAX - LTHREAD_PRIORITY_MIN + 1)

#define LTHREAD_PRIORITY_NORMAL \
	(LTHREAD_PRIORITY_MIN + LTHREAD_PRIORITY_MAX) / 2

#define LTHREAD_PRIORITY_LOW  \
	(LTHREAD_PRIORITY_MIN + LTHREAD_PRIORITY_NORMAL) / 2
#define LTHREAD_PRIORITY_HIGH \
	(LTHREAD_PRIORITY_MAX + LTHREAD_PRIORITY_NORMAL) / 2

#define LTHREAD_PRIORITY_DEFAULT \
	LTHREAD_PRIORITY_NORMAL

#endif /* KERNEL_LTHREAD_PRIORITY_H_ */
