/**
 * @file
 *
 * @author Andrey Kokorev
 */

#ifndef KERNEL_LWTHREAD_PRIORITY_H_
#define KERNEL_LWTHREAD_PRIORITY_H_

#include <kernel/sched/sched_priority.h>

#define LWTHREAD_PRIORITY_MIN SCHED_PRIORITY_MAX - 255   /**< The lowest priority is 0. */
#define LWTHREAD_PRIORITY_MAX SCHED_PRIORITY_MAX /**< The highest priority. */

/** Total amount of valid priorities. */
#define LWTHREAD_PRIORITY_TOTAL \
	(LWTHREAD_PRIORITY_MAX - LWTHREAD_PRIORITY_MIN + 1)

#define LWTHREAD_PRIORITY_NORMAL \
	(LWTHREAD_PRIORITY_MIN + LWTHREAD_PRIORITY_MAX) / 2

#define LWTHREAD_PRIORITY_LOW  \
	(LWTHREAD_PRIORITY_MIN + LWTHREAD_PRIORITY_NORMAL) / 2
#define LWTHREAD_PRIORITY_HIGH \
	(LWTHREAD_PRIORITY_MAX + LWTHREAD_PRIORITY_NORMAL) / 2

#define LWTHREAD_PRIORITY_DEFAULT \
	LWTHREAD_PRIORITY_NORMAL

#endif /* KERNEL_LWTHREAD_PRIORITY_H_ */
