
$_MODS += nxt_lcd_picture
$_MODS += nxt_splash
$_MODS += nxt_fill

$_SRCS-nxt_lcd_picture += picture_embox.c
$_DEPS-nxt_lcd_picture += $(PLATFORM).driver.nxt_lcd

$_SRCS-nxt_splash += abc_embox.c
$_DEPS-nxt_splash += $(PLATFORM).driver.nxt_lcd

$_SRCS-nxt_fill += test_fill.c
$_DEPS-nxt_fill += $(PLATFORM).driver.nxt_lcd
