$_PACKAGE := core.kernel.thread.sched_policy

$_APIS                    += api

$_MODS                    += trivial
$_SRCS-trivial            += trivial.c
$_PROVIDES-trivial        += api

$_MODS                    += priority_based
$_SRCS-priority_based     += priority_based.c
$_PROVIDES-priority_based += api
