$_PACKAGE := embox.kernel.thread.sched_policy

$_APIS                    += api

$_MODS                    += sched_trivial
$_SRCS-sched_trivial      += sched_trivial.[c|h]
$_PROVIDES-sched_trivial  += api

$_MODS                    += priority_based
$_SRCS-priority_based     += priority_based.[c|h]
$_PROVIDES-priority_based += api
