
PKG_NAME := efm32bsp_libs

REPO_NAME := embedded_software

PKG_SOURCES := https://googledrive.com/host/0B7g4WwjaJX23ZExQU2hHTzYyRm8/efm32bsp_libs.tar.gz \
	http://www.silabs.com/Support%20Documents/Software/efm32zg-stk3200-bsp.zip

include $(EXTBLD_LIB)
