
PKG_NAME := efm32bsp_libs

REPO_NAME := embedded_software

PKG_SOURCES := https://googledrive.com/host/0B7g4WwjaJX23ZExQU2hHTzYyRm8/efm32bsp_libs.tar.gz \
	http://www.silabs.com/Support%20Documents/Software/efm32zg-stk3200-bsp.zip
PKG_MD5     := c30ea25f245022633d865184f627a8cd 0b356f581486c99bca9617b5791a06c6

include $(EXTBLD_LIB)
