$_PACKAGE := embox.driver.watchdog

$_MODS               += at91_wdtc
$_SRCS-at91_wdtc     += at91_wdtc.c
$_PROVIDES-at91_wdtc += embox.hal.watchdog

$_MODS               += noimpl
$_SRCS-noimpl        += noimpl.c
$_PROVIDES-noimpl    += embox.hal.watchdog
