$_PACKAGE := embox.kernel

$_MODS += evdispatch
$_MODS += evdispatch2

$_DEPS-evdispatch += embox.mem.slab
$_REQUIRE-evdispatch += embox.mem.slab
$_SRCS-evdispatch = evdispatch.c
$_SRCS-evdispatch2 = evdispatch2.c
