<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="build"
    nsURI="http://www.mybuild.org/myfile/Build" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Build">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="ecore:EClass configfile.ecore#//Configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//ModuleInstance" containment="true" eOpposite="#//ModuleInstance/build"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="build" eType="#//Build"
        eOpposite="#//Build/modules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass myfile.ecore#//ModuleType"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependent" upperBound="-1"
        eType="#//ModuleInstance" resolveProxies="false" eOpposite="#//ModuleInstance/depends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
        eType="#//ModuleInstance" volatile="true" transient="true" derived="true"
        resolveProxies="false" eOpposite="#//ModuleInstance/dependent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ModuleInstance" volatile="true" transient="true" derived="true"
        resolveProxies="false" eOpposite="#//ModuleInstance/contained"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contained" eType="#//ModuleInstance"
        resolveProxies="false" eOpposite="#//ModuleInstance/contents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//OptionInstance" containment="true" eOpposite="#//OptionInstance/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterDepends" upperBound="-1"
        eType="#//ModuleInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeMember" eType="ecore:EClass configfile.ecore#//Include"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ModuleInstance"
        eOpposite="#//ModuleInstance/options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="ecore:EClass myfile.ecore#//Option"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass myfile.ecore#//Literal"/>
  </eClassifiers>
</ecore:EPackage>
