<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configFile"
    nsURI="http://www.mybuild.org/myfile/ConfigFile" nsPrefix="cfg">
  <eClassifiers xsi:type="ecore:EClass" name="FileContentRoot" eSuperTypes="../model/emodel.ecore#//ENamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//Configuration"
        containment="true" eOpposite="#//Configuration/fileContentRoot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="../model/emodel.ecore#//ENamedObject myfile.ecore#//AnnotationTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileContentRoot" eType="#//FileContentRoot"
        eOpposite="#//FileContentRoot/configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Include" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include" eSuperTypes="myfile.ecore#//AnnotationTarget ../model/emodel.ecore#//ENamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" upperBound="-1"
        eType="ecore:EClass myfile.ecore#//ModuleType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionBindings" upperBound="-1"
        eType="ecore:EClass myfile.ecore#//OptionBinding" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
