<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configFile"
    nsURI="http://www.mybuild.org/myfile/ConfigFile" nsPrefix="cfg">
  <eClassifiers xsi:type="ecore:EClass" name="FileContent" eSuperTypes="emodel.ecore#//ENamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//Configuration" containment="true" eOpposite="#//Configuration/fileContent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" abstract="true" eSuperTypes="emodel.ecore#//ENamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileContent" eType="#//FileContent"
        eOpposite="#//FileContent/configurations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" eType="#//Include"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Include">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass myfile.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionBindings" upperBound="-1"
        eType="#//OptionBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionBinding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType emodel.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
