# Generated by GOLD Parser Builder using Mybuild program template.

# Symbol constructors for 'ConfigFile' grammar.

include mk/mybuild/common-symbols.mk

#
# Optimized contructors for constant terminals (i.e. keywords and punctuation).
#

$(gold_grammar)_create-configuration    := configuration
$(gold_grammar)_create-import           := import
$(gold_grammar)_create-include          := include
$(gold_grammar)_create-package          := package

