# Generated by Xpand using M2Make template.

# Metamodel implementation for 'myFile' package.

ifndef __mybuild_myfile_metamodel_impl_mk
__mybuild_myfile_metamodel_impl_mk := $(lastword $(MAKEFILE_LIST))

# Creates and initializes contents of 'myFile' meta model.
define class-MyFileMetaModelImpl
	$(super MyFileMetaModel)

	$(super MetaModelImpl)

	# Create necessary objects.

	$(set Model,
		$(invoke createMetaClass,Model))
	$(set Model_Package,
		$(invoke createMetaReference,package,$(get Model)))
	$(set Model_Imports,
		$(invoke createMetaReference,imports,$(get Model)))
	$(set Model_Entities,
		$(invoke createMetaReference,entities,$(get Model)))

	$(set Package,
		$(invoke createMetaClass,Package))
	$(set Package_Name,
		$(invoke createMetaAttribute,name,$(get Package)))

	$(set Import,
		$(invoke createMetaClass,Import))
	$(set Import_ImportedNamespace,
		$(invoke createMetaAttribute,importedNamespace,$(get Import)))

	$(set Entity,
		$(invoke createMetaClass,Entity))
	$(set Entity_Name,
		$(invoke createMetaAttribute,name,$(get Entity)))

	$(set Interface,
		$(invoke createMetaClass,Interface))
	$(set Interface_SuperType,
		$(invoke createMetaReference,superType,$(get Interface)))
	$(set Interface_Attributes,
		$(invoke createMetaReference,attributes,$(get Interface)))

	$(set InterfaceProperty,
		$(invoke createMetaClass,InterfaceProperty))

	$(set Feature,
		$(invoke createMetaClass,Feature))
	$(set Feature_Name,
		$(invoke createMetaAttribute,name,$(get Feature)))
	$(set Feature_SuperType,
		$(invoke createMetaReference,superType,$(get Feature)))

	$(set Module,
		$(invoke createMetaClass,Module))
	$(set Module_Static,
		$(invoke createMetaAttribute,static,$(get Module)))
	$(set Module_Abstract,
		$(invoke createMetaAttribute,abstract,$(get Module)))
	$(set Module_SuperType,
		$(invoke createMetaReference,superType,$(get Module)))
	$(set Module_SubTypes,
		$(invoke createMetaReference,subTypes,$(get Module)))
	$(set Module_Attributes,
		$(invoke createMetaReference,attributes,$(get Module)))
	$(set Module_Depends,
		$(invoke createMetaReference,depends,$(get Module)))
	$(set Module_Dependent,
		$(invoke createMetaReference,dependent,$(get Module)))

	$(set ModuleProperty,
		$(invoke createMetaClass,ModuleProperty))

	$(set Depends,
		$(invoke createMetaClass,Depends))
	$(set Depends_Modules,
		$(invoke createMetaReference,modules,$(get Depends)))

	$(set FeatureModuleProperty,
		$(invoke createMetaClass,FeatureModuleProperty))
	$(set FeatureModuleProperty_Features,
		$(invoke createMetaReference,features,$(get FeatureModuleProperty)))

	$(set FilenameModuleProperty,
		$(invoke createMetaClass,FilenameModuleProperty))
	$(set FilenameModuleProperty_Files,
		$(invoke createMetaReference,files,$(get FilenameModuleProperty)))

	$(set Filename,
		$(invoke createMetaClass,Filename))
	$(set Filename_Name,
		$(invoke createMetaAttribute,name,$(get Filename)))

	$(set Requires,
		$(invoke createMetaClass,Requires))

	$(set Provides,
		$(invoke createMetaClass,Provides))

	$(set Sources,
		$(invoke createMetaClass,Sources))

	$(set Objects,
		$(invoke createMetaClass,Objects))

	# Initialize.

	$(invoke initMetaClass,$(get Model),)
	$(invoke initMetaReference,$(get Model_Package),$(get Package),)
	$(invoke initMetaReference,$(get Model_Imports),$(get Import),)
	$(invoke initMetaReference,$(get Model_Entities),$(get Entity),)

	$(invoke initMetaClass,$(get Package),)
	$(invoke initMetaAttribute,$(get Package_Name),)# NIY.

	$(invoke initMetaClass,$(get Import),)
	$(invoke initMetaAttribute,$(get Import_ImportedNamespace),)# NIY.

	$(invoke initMetaClass,$(get Entity),)
	$(invoke initMetaAttribute,$(get Entity_Name),)# NIY.

	$(invoke initMetaClass,$(get Interface),
		$(get Entity))
	$(invoke initMetaReference,$(get Interface_SuperType),$(get Interface),)
	$(invoke initMetaReference,$(get Interface_Attributes),$(get InterfaceProperty),)

	$(invoke initMetaClass,$(get InterfaceProperty),)

	$(invoke initMetaClass,$(get Feature),
		$(get InterfaceProperty))
	$(invoke initMetaAttribute,$(get Feature_Name),)# NIY.
	$(invoke initMetaReference,$(get Feature_SuperType),$(get Feature),)

	$(invoke initMetaClass,$(get Module),
		$(get Entity))
	$(invoke initMetaAttribute,$(get Module_Static),)# NIY.
	$(invoke initMetaAttribute,$(get Module_Abstract),)# NIY.
	$(invoke initMetaReference,$(get Module_SuperType),$(get Module),$(get Module_SubTypes))
	$(invoke initMetaReference,$(get Module_SubTypes),$(get Module),$(get Module_SuperType))
	$(invoke initMetaReference,$(get Module_Attributes),$(get ModuleProperty),)
	$(invoke initMetaReference,$(get Module_Depends),$(get Module),$(get Module_Dependent))
	$(invoke initMetaReference,$(get Module_Dependent),$(get Module),$(get Module_Depends))

	$(invoke initMetaClass,$(get ModuleProperty),)

	$(invoke initMetaClass,$(get Depends),
		$(get ModuleProperty))
	$(invoke initMetaReference,$(get Depends_Modules),$(get Module),)

	$(invoke initMetaClass,$(get FeatureModuleProperty),
		$(get ModuleProperty))
	$(invoke initMetaReference,$(get FeatureModuleProperty_Features),$(get Feature),)

	$(invoke initMetaClass,$(get FilenameModuleProperty),
		$(get ModuleProperty))
	$(invoke initMetaReference,$(get FilenameModuleProperty_Files),$(get Filename),)

	$(invoke initMetaClass,$(get Filename),)
	$(invoke initMetaAttribute,$(get Filename_Name),)# NIY.

	$(invoke initMetaClass,$(get Requires),
		$(get FeatureModuleProperty))

	$(invoke initMetaClass,$(get Provides),
		$(get FeatureModuleProperty))

	$(invoke initMetaClass,$(get Sources),
		$(get FilenameModuleProperty))

	$(invoke initMetaClass,$(get Objects),
		$(get FilenameModuleProperty))
endef

endif # __mybuild_myfile_metamodel_impl_mk

