<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myFile"
    nsURI="http://www.mybuild.org/myfile/MyFile" nsPrefix="myFile">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//Package"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//InterfaceProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//InterfaceProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Module"
        eOpposite="#//Module/subTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTypes" upperBound="-1"
        eType="#//Module" eOpposite="#//Module/superType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//ModuleProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
        eType="#//Module" eOpposite="#//Module/dependent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependent" upperBound="-1"
        eType="#//Module" eOpposite="#//Module/depends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Depends" eSuperTypes="#//ModuleProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" unique="false"
        upperBound="-1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModuleProperty" eSuperTypes="#//ModuleProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" unique="false"
        upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilenameModuleProperty" eSuperTypes="#//ModuleProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//Filename" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filename">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requires" eSuperTypes="#//FeatureModuleProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Provides" eSuperTypes="#//FeatureModuleProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sources" eSuperTypes="#//FilenameModuleProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Objects" eSuperTypes="#//FilenameModuleProperty"/>
</ecore:EPackage>
