# Generated by Xpand using M2Make template.

# Metamodel implementation for 'myFile' package.

ifndef __mybuild_myfile_metamodel_impl_mk
__mybuild_myfile_metamodel_impl_mk := $(lastword $(MAKEFILE_LIST))

# Creates and initializes contents of 'myFile' meta model.
define class-MyFileMetaModelImpl
	$(super MyFileMetaModel)

	$(super MetaModelImpl)

	# Create necessary objects.

	$(set Model,
		$(invoke createMetaClass,Model))
	$(set Model_Package,
		$(invoke createMetaReference,package,$(get Model)))
	$(set Model_Imports,
		$(invoke createMetaReference,imports,$(get Model)))
	$(set Model_Entities,
		$(invoke createMetaReference,entities,$(get Model)))

	$(set Package,
		$(invoke createMetaClass,Package))
	$(set Package_Name,
		$(invoke createMetaAttribute,name,$(get Package)))

	$(set Import,
		$(invoke createMetaClass,Import))
	$(set Import_ImportedNamespace,
		$(invoke createMetaAttribute,importedNamespace,$(get Import)))

	$(set Entity,
		$(invoke createMetaClass,Entity))
	$(set Entity_Name,
		$(invoke createMetaAttribute,name,$(get Entity)))

	$(set Interface,
		$(invoke createMetaClass,Interface))
	$(set Interface_SuperType,
		$(invoke createMetaReference,superType,$(get Interface)))
	$(set Interface_Features,
		$(invoke createMetaReference,features,$(get Interface)))
	$(set Interface_SubTypes,
		$(invoke createMetaReference,subTypes,$(get Interface)))

	$(set Feature,
		$(invoke createMetaClass,Feature))
	$(set Feature_Name,
		$(invoke createMetaAttribute,name,$(get Feature)))
	$(set Feature_SuperType,
		$(invoke createMetaReference,superType,$(get Feature)))
	$(set Feature_Interface,
		$(invoke createMetaReference,interface,$(get Feature)))
	$(set Feature_ProvidedBy,
		$(invoke createMetaReference,providedBy,$(get Feature)))
	$(set Feature_RequiredBy,
		$(invoke createMetaReference,requiredBy,$(get Feature)))
	$(set Feature_SubTypes,
		$(invoke createMetaReference,subTypes,$(get Feature)))

	$(set Module,
		$(invoke createMetaClass,Module))
	$(set Module_Static,
		$(invoke createMetaAttribute,static,$(get Module)))
	$(set Module_Abstract,
		$(invoke createMetaAttribute,abstract,$(get Module)))
	$(set Module_SuperType,
		$(invoke createMetaReference,superType,$(get Module)))
	$(set Module_SubTypes,
		$(invoke createMetaReference,subTypes,$(get Module)))
	$(set Module_Depends,
		$(invoke createMetaReference,depends,$(get Module)))
	$(set Module_Dependent,
		$(invoke createMetaReference,dependent,$(get Module)))
	$(set Module_Provides,
		$(invoke createMetaReference,provides,$(get Module)))
	$(set Module_Requires,
		$(invoke createMetaReference,requires,$(get Module)))

	$(set Filename,
		$(invoke createMetaClass,Filename))
	$(set Filename_Name,
		$(invoke createMetaAttribute,name,$(get Filename)))

	# Initialize.

	$(invoke initMetaClass,$(get Model),)
	$(invoke initMetaReference,$(get Model_Package),$(get Package),)
	$(invoke initMetaReference,$(get Model_Imports),$(get Import),)
	$(invoke initMetaReference,$(get Model_Entities),$(get Entity),)

	$(invoke initMetaClass,$(get Package),)
	$(invoke initMetaAttribute,$(get Package_Name),)# NIY.

	$(invoke initMetaClass,$(get Import),)
	$(invoke initMetaAttribute,$(get Import_ImportedNamespace),)# NIY.

	$(invoke initMetaClass,$(get Entity),)
	$(invoke initMetaAttribute,$(get Entity_Name),)# NIY.

	$(invoke initMetaClass,$(get Interface),
		$(get Entity))
	$(invoke initMetaReference,$(get Interface_SuperType),$(get Interface),$(get Interface_SubTypes))
	$(invoke initMetaReference,$(get Interface_Features),$(get Feature),$(get Feature_Interface))
	$(invoke initMetaReference,$(get Interface_SubTypes),$(get Interface),$(get Interface_SuperType))

	$(invoke initMetaClass,$(get Feature),)
	$(invoke initMetaAttribute,$(get Feature_Name),)# NIY.
	$(invoke initMetaReference,$(get Feature_SuperType),$(get Feature),$(get Feature_SubTypes))
	$(invoke initMetaReference,$(get Feature_Interface),$(get Interface),$(get Interface_Features))
	$(invoke initMetaReference,$(get Feature_ProvidedBy),$(get Module),$(get Module_Provides))
	$(invoke initMetaReference,$(get Feature_RequiredBy),$(get Module),$(get Module_Requires))
	$(invoke initMetaReference,$(get Feature_SubTypes),$(get Feature),$(get Feature_SuperType))

	$(invoke initMetaClass,$(get Module),
		$(get Entity))
	$(invoke initMetaAttribute,$(get Module_Static),)# NIY.
	$(invoke initMetaAttribute,$(get Module_Abstract),)# NIY.
	$(invoke initMetaReference,$(get Module_SuperType),$(get Module),$(get Module_SubTypes))
	$(invoke initMetaReference,$(get Module_SubTypes),$(get Module),$(get Module_SuperType))
	$(invoke initMetaReference,$(get Module_Depends),$(get Module),$(get Module_Dependent))
	$(invoke initMetaReference,$(get Module_Dependent),$(get Module),$(get Module_Depends))
	$(invoke initMetaReference,$(get Module_Provides),$(get Feature),$(get Feature_ProvidedBy))
	$(invoke initMetaReference,$(get Module_Requires),$(get Feature),$(get Feature_RequiredBy))

	$(invoke initMetaClass,$(get Filename),)
	$(invoke initMetaAttribute,$(get Filename_Name),)# NIY.
endef

$(def_all)

endif # __mybuild_myfile_metamodel_impl_mk

