# Generated by Xpand using M2Make template.

# Implementation of factory for 'myFile' model.

ifndef __mybuild_myfile_factory_impl_mk
__mybuild_myfile_factory_impl_mk := $(lastword $(MAKEFILE_LIST))

# Implements methods for creating objects of 'myFile' model.
define class-MyFileFactoryImpl
	$(super MyFileFactory)

	$(super NodeFactoryImpl)

	$(method createModel,
		$(new ModelImpl))

	$(method createPackage,
		$(new PackageImpl))

	$(method createImport,
		$(new ImportImpl))

	$(method createEntity,
		$(new EntityImpl))

	$(method createInterface,
		$(new InterfaceImpl))
	$(method createReferenceToInterface,
		$(new ReferenceToInterfaceImpl,$(value 1)))

	$(method createInterfaceProperty,
		$(new InterfacePropertyImpl))

	$(method createFeature,
		$(new FeatureImpl))
	$(method createReferenceToFeature,
		$(new ReferenceToFeatureImpl,$(value 1)))

	$(method createModule,
		$(new ModuleImpl))
	$(method createReferenceToModule,
		$(new ReferenceToModuleImpl,$(value 1)))

	$(method createModuleProperty,
		$(new ModulePropertyImpl))

	$(method createDepends,
		$(new DependsImpl))

	$(method createFeatureModuleProperty,
		$(new FeatureModulePropertyImpl))

	$(method createFilenameModuleProperty,
		$(new FilenameModulePropertyImpl))

	$(method createFilename,
		$(new FilenameImpl))

	$(method createRequires,
		$(new RequiresImpl))

	$(method createProvides,
		$(new ProvidesImpl))

	$(method createSources,
		$(new SourcesImpl))

	$(method createObjects,
		$(new ObjectsImpl))
endef

endif # __mybuild_myfile_factory_impl_mk

