# Generated by Xpand using M2Make template.

# Model of 'myFile' package.

ifndef __mybuild_myfile_model_mk
__mybuild_myfile_model_mk := 1

include mk/model/model_impl.mk

#
# Model object 'FileContentRoot'.
#
# The following features are defined:
#   - reference 'types'
#   - attribute 'imports'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyFileContentRoot
	# Extends 'ENamedObject' class.
	$(eobject MyFile_FileContentRoot,
		MyFileContentRoot,ENamedObject,)

	# Property 'types... : MyType'.
	$(eobject-reference MyFile_FileContentRoot_types,
		types,MyType,fileContentRoot,changeable many containment)

	# Property 'imports...'.
	$(eobject-attribute MyFile_FileContentRoot_imports,
		imports,changeable many)

	# PROTECTED REGION ID(MyFile_FileContentRoot) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'Type'.
#
# The following features are defined:
#   - reference 'fileContentRoot'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyType # abstract
	# Extends 'ENamedObject', 'MyAnnotationTarget' classes.
	$(eobject MyFile_Type,
		MyType,ENamedObject MyAnnotationTarget,abstract)

	# Property 'fileContentRoot : MyFileContentRoot'.
	$(eobject-reference MyFile_Type_fileContentRoot,
		fileContentRoot,MyFileContentRoot,types,changeable container)

	# PROTECTED REGION ID(MyFile_Type) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'AnnotationType'.
#
# The following features are defined:
#   - reference 'options'
#
# The following features are inherited from 'Type':
#   - reference 'fileContentRoot'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyAnnotationType
	# Extends 'MyType' class.
	$(eobject MyFile_AnnotationType,
		MyAnnotationType,MyType,)

	# Property 'options... : MyOption'.
	$(eobject-reference MyFile_AnnotationType_options,
		options,MyOption,,changeable many containment)

	# PROTECTED REGION ID(MyFile_AnnotationType) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'Annotation'.
#
# The following features are defined:
#   - reference 'type'
#   - reference 'target'
#   - reference 'bindings'
#
define class-MyAnnotation
	# Extends 'EObject' class (implicitly).
	$(eobject MyFile_Annotation,
		MyAnnotation,,)

	# Property 'type : MyAnnotationType'.
	# Property 'type_link : ELink'.
	$(eobject-reference MyFile_Annotation_type,
		type,MyAnnotationType,,changeable linkable)

	# Property 'target : MyAnnotationTarget'.
	$(eobject-reference MyFile_Annotation_target,
		target,MyAnnotationTarget,annotations,changeable container)

	# Property 'bindings... : MyOptionBinding'.
	$(eobject-reference MyFile_Annotation_bindings,
		bindings,MyOptionBinding,,changeable many containment)

	# PROTECTED REGION ID(MyFile_Annotation) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'AnnotationTarget'.
#
# The following features are defined:
#   - reference 'annotations'
#
define class-MyAnnotationTarget # abstract
	# Extends 'EObject' class (implicitly).
	$(eobject MyFile_AnnotationTarget,
		MyAnnotationTarget,,abstract)

	# Property 'annotations... : MyAnnotation'.
	$(eobject-reference MyFile_AnnotationTarget_annotations,
		annotations,MyAnnotation,target,changeable many containment)

	# PROTECTED REGION ID(MyFile_AnnotationTarget) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'AnnotatedLink'.
#
# No features or operations defined.
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ELink':
#   - reference 'eMetaReference'
#   - attribute 'eMetaReferenceId'
#   - attribute 'eResource'
#   - attribute 'name'
#   - attribute 'origin'
#   - operation 'eSource'
#   - operation 'eTarget'
#   - operation 'resolve'
#   - operation 'deresolve'
#
define class-MyAnnotatedLink
	# Extends 'ELink', 'MyAnnotationTarget' classes.
	$(eobject MyFile_AnnotatedLink,
		MyAnnotatedLink,ELink MyAnnotationTarget,)

	# PROTECTED REGION ID(MyFile_AnnotatedLink) ENABLED START

	$(method eContainer : EObject,$(invoke eSource))

	$(if $(value 1),
		$(set name,$1))
	$(if $(value 2),
		$(set origin,$2))
	# PROTECTED REGION END
endef

#
# Model object 'Interface'.
#
# The following features are defined:
#   - reference 'features'
#
# The following features are inherited from 'Type':
#   - reference 'fileContentRoot'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyInterface
	# Extends 'MyType' class.
	$(eobject MyFile_Interface,
		MyInterface,MyType,)

	# Property 'features... : MyFeature'.
	$(eobject-reference MyFile_Interface_features,
		features,MyFeature,interface,changeable many containment)

	# PROTECTED REGION ID(MyFile_Interface) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'Feature'.
#
# The following features are defined:
#   - reference 'interface'
#   - reference 'providedBy'
#   - reference 'requiredBy'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyFeature
	# Extends 'ENamedObject' class.
	$(eobject MyFile_Feature,
		MyFeature,ENamedObject,)

	# Property 'interface : MyInterface'.
	$(eobject-reference MyFile_Feature_interface,
		interface,MyInterface,features,changeable container)

	# Property 'providedBy... : MyModule'.
	# Property 'providedBy_links... : ELink'.
	$(eobject-reference MyFile_Feature_providedBy,
		providedBy,MyModule,provides,changeable many linkable)

	# Property 'requiredBy... : MyModule'.
	# Property 'requiredBy_links... : ELink'.
	$(eobject-reference MyFile_Feature_requiredBy,
		requiredBy,MyModule,requires,changeable many linkable)

	# PROTECTED REGION ID(MyFile_Feature) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'Module'.
#
# The following features and operations are defined:
#   - attribute 'modifiers'
#   - attribute 'static'
#   - attribute 'abstract'
#   - reference 'depends'
#   - reference 'dependsMembers'
#   - reference 'dependent'
#   - reference 'provides'
#   - reference 'requires'
#   - reference 'sources'
#   - reference 'objects'
#   - reference 'options'
#   - reference 'allOptions'
#   - reference 'subTypes'
#   - reference 'superType'
#   - reference 'allSubTypes'
#   - reference 'allSuperTypes'
#   - operation 'isSubTypeOf'
#   - operation 'isSuperTypeOf'
#
# The following features are inherited from 'Type':
#   - reference 'fileContentRoot'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyModule
	# Extends 'MyType' class.
	$(eobject MyFile_Module,
		MyModule,MyType,)

	# Property 'modifiers'.
	$(eobject-attribute MyFile_Module_modifiers,
		modifiers,changeable)

	# Attribute 'static': derived.
	$(property isStatic)
	# PROTECTED REGION ID(MyFile_Module_isStatic) ENABLED START
	$(getter isStatic,
		$(filter static,$(get-field modifiers)))
	$(setter isStatic,
		$(if $1,$(set+ modifiers,static),$(set- modifiers,static)))
	# PROTECTED REGION END

	# Attribute 'abstract': derived.
	$(property isAbstract)
	# PROTECTED REGION ID(MyFile_Module_isAbstract) ENABLED START
	$(getter isAbstract,
		$(filter abstract,$(get-field modifiers)))
	$(setter isAbstract,
		$(if $1,$(set+ modifiers,abstract),$(set- modifiers,abstract)))
	# PROTECTED REGION END

	# Property 'depends... : MyModule'.
	# Property 'depends_links... : ELink'.
	$(eobject-reference MyFile_Module_depends,
		depends,MyModule,dependent,changeable many linkable)

	# Reference 'dependsMembers' [0..*]: containment, derived.
	$(property dependsMembers... : MyAnnotatedLink)
	# PROTECTED REGION ID(MyFile_Module_dependsMembers) ENABLED START
	$(getter dependsMembers,
		$(get depends_links))
#	# TODO Uncomment and implement me.
	$(setter dependsMembers,
		$(error $0($1): NIY))
#	# TODO Uncomment and implement us.
	$(setter+ dependsMembers,
		$(error $0($1): NIY))
	$(setter- dependsMembers,
		$(error $0($1): NIY))
	# PROTECTED REGION END

	# Property 'dependent... : MyModule'.
	# Property 'dependent_links... : ELink'.
	$(eobject-reference MyFile_Module_dependent,
		dependent,MyModule,depends,changeable many linkable)

	# Property 'provides... : MyFeature'.
	# Property 'provides_links... : ELink'.
	$(eobject-reference MyFile_Module_provides,
		provides,MyFeature,providedBy,changeable many linkable)

	# Property 'requires... : MyFeature'.
	# Property 'requires_links... : ELink'.
	$(eobject-reference MyFile_Module_requires,
		requires,MyFeature,requiredBy,changeable many linkable)

	# Property 'sources... : MyFileMember'.
	$(eobject-reference MyFile_Module_sources,
		sources,MyFileMember,,changeable many containment)

	# Property 'objects... : MyFileMember'.
	$(eobject-reference MyFile_Module_objects,
		objects,MyFileMember,,changeable many containment)

	# Property 'options... : MyOption'.
	$(eobject-reference MyFile_Module_options,
		options,MyOption,,changeable many containment)

	# Reference 'allOptions' [0..1]: derived.
	$(property allOptions : MyOption)
	# PROTECTED REGION ID(MyFile_Module_allOptions) ENABLED START
	$(getter allOptions,
		$(with $(for opt <- $(get options),
				$(get opt->name)),
			$(get options) \
			$(for super <- $(get superType),
				superOpt <- $(get super->allOptions),
				$(if $(filter $1,$(get superOpt->name)),,
			       		$(superOpt)))))


	$(setter allOptions,
		$(error $0($1): NIY))
	# PROTECTED REGION END

	# Property 'subTypes... : MyModule'.
	# Property 'subTypes_links... : ELink'.
	$(eobject-reference MyFile_Module_subTypes,
		subTypes,MyModule,superType,changeable many linkable)

	# Property 'superType : MyModule'.
	# Property 'superType_link : ELink'.
	$(eobject-reference MyFile_Module_superType,
		superType,MyModule,subTypes,changeable linkable)

	# Reference 'allSubTypes' [0..*]: bidirectional, derived, read-only.
	$(property allSubTypes... : MyModule)
	# PROTECTED REGION ID(MyFile_Module_allSubTypes) ENABLED START
	$(getter allSubTypes,
		$(for subType <- $(get subTypes),
			$(subType) \
			$(get subType->allSubTypes)))
	# PROTECTED REGION END

	# Reference 'allSuperTypes' [0..*]: bidirectional, derived, read-only.
	$(property allSuperTypes... : MyModule)
	# PROTECTED REGION ID(MyFile_Module_allSuperTypes) ENABLED START
	$(getter allSuperTypes,
		$(get superType) $(foreach s,$(get superType),$(get s->allSuperTypes)))
	# PROTECTED REGION END

	# Method 'isSubTypeOf'.
	#   1. another : MyModule
	# PROTECTED REGION ID(MyFile_Module_isSubTypeOf) ENABLED START
#	# TODO Uncomment and implement me.
#	$(method isSubTypeOf,
#		$(error $0($1): NIY))
	# PROTECTED REGION END

	# Method 'isSuperTypeOf'.
	#   1. another : MyModule
	# PROTECTED REGION ID(MyFile_Module_isSuperTypeOf) ENABLED START
#	# TODO Uncomment and implement me.
	$(method isSuperTypeOf,
		$(error $0($1): NIY))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_Module) ENABLED START
	$(setter modifiers,
		$(set-field modifiers,$(sort $1)))
	# PROTECTED REGION END
endef

#
# Model object 'FileMember'.
#
# The following features are defined:
#   - attribute 'fileName'
#   - attribute 'fileFullName'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
define class-MyFileMember
	# Extends 'MyAnnotationTarget' class.
	$(eobject MyFile_FileMember,
		MyFileMember,MyAnnotationTarget,)

	# Property 'fileName'.
	$(eobject-attribute MyFile_FileMember_fileName,
		fileName,changeable)

	# Attribute 'fileFullName': derived, read-only.
	$(property fileFullName)
	# PROTECTED REGION ID(MyFile_FileMember_fileFullName) ENABLED START
#	# TODO Uncomment and implement me.
	$(getter fileFullName,
		$(dir $(get $(get eResource).fileName))$(get fileName))

	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_FileMember) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'Option'.
#
# The following features and operations are defined:
#   - reference 'defaultValue'
#   - operation 'validateValue'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyOption # abstract
	# Extends 'ENamedObject', 'MyAnnotationTarget' classes.
	$(eobject MyFile_Option,
		MyOption,ENamedObject MyAnnotationTarget,abstract)

	# Property 'defaultValue : MyOptionValue'.
	$(eobject-reference MyFile_Option_defaultValue,
		defaultValue,MyOptionValue,,changeable containment)

	# Method 'validateValue'.
	# PROTECTED REGION ID(MyFile_Option_validateValue) ENABLED START
#	# TODO Uncomment and implement me.
	$(method validateValue,
		$(error $0(): NIY))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_Option) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'StringOption'.
#
# The following operations are defined:
#   - operation 'validateValue'
#
# The following features and operations are inherited from 'Option':
#   - reference 'defaultValue'
#   - operation 'validateValue'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyStringOption
	# Extends 'MyOption' class.
	$(eobject MyFile_StringOption,
		MyStringOption,MyOption,)

	# Method 'validateValue'.
	# PROTECTED REGION ID(MyFile_StringOption_validateValue) ENABLED START
#	# TODO Uncomment and implement me.
	$(method validateValue,
		$(invoke MyFile_StringOptionValue->isInstance,$1))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_StringOption) ENABLED START
	# PROTECTED REGION END
endef

#
# Model object 'NumberOption'.
#
# The following operations are defined:
#   - operation 'validateValue'
#
# The following features and operations are inherited from 'Option':
#   - reference 'defaultValue'
#   - operation 'validateValue'
#
# The following features are inherited from 'AnnotationTarget':
#   - reference 'annotations'
#
# The following features and operations are inherited from 'ENamedObject':
#   - attribute 'name'
#   - attribute 'qualifiedName'
#   - attribute 'origin'
#   - operation 'eInverseResolvedLinks'
#
define class-MyNumberOption
	# Extends 'MyOption' class.
	$(eobject MyFile_NumberOption,
		MyNumberOption,MyOption,)

	# Method 'validateValue'.
	# PROTECTED REGION ID(MyFile_NumberOption_validateValue) ENABLED START
#	# TODO Uncomment and implement me.
	$(method validateValue,
		$(invoke MyFile_NumberOptionValue->isInstance,$1))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_NumberOption) ENABLED START
	# PROTECTED REGION END
endef

#
# Model object 'OptionValue'.
#
# The following features and operations are defined:
#   - attribute 'value'
#   - operation 'toString'
#
define class-MyOptionValue # abstract
	# Extends 'EObject' class (implicitly).
	$(eobject MyFile_OptionValue,
		MyOptionValue,,abstract)

	# Property 'value'.
	$(eobject-attribute MyFile_OptionValue_value,
		value,changeable)

	# Method 'toString'.
	# PROTECTED REGION ID(MyFile_OptionValue_toString) ENABLED START
#	# TODO Uncomment and implement me.
	$(method toString,
		$(error $0(): NIY))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_OptionValue) ENABLED START
#	# TODO Add custom implementation here and remove this comment.
	# PROTECTED REGION END
endef

#
# Model object 'StringOptionValue'.
#
# The following operations are defined:
#   - operation 'toString'
#
# The following features and operations are inherited from 'OptionValue':
#   - attribute 'value'
#   - operation 'toString'
#
define class-MyStringOptionValue
	# Extends 'MyOptionValue' class.
	$(eobject MyFile_StringOptionValue,
		MyStringOptionValue,MyOptionValue,)

	# Method 'toString'.
	# PROTECTED REGION ID(MyFile_StringOptionValue_toString) ENABLED START
#	# TODO Uncomment and implement me.
	$(method toString,
		$(error $0(): NIY))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_StringOptionValue) ENABLED START
	$(if $(value 1),
		$(set value,$1))
	# PROTECTED REGION END
endef

#
# Model object 'NumberOptionValue'.
#
# The following operations are defined:
#   - operation 'toString'
#
# The following features and operations are inherited from 'OptionValue':
#   - attribute 'value'
#   - operation 'toString'
#
define class-MyNumberOptionValue
	# Extends 'MyOptionValue' class.
	$(eobject MyFile_NumberOptionValue,
		MyNumberOptionValue,MyOptionValue,)

	# Method 'toString'.
	# PROTECTED REGION ID(MyFile_NumberOptionValue_toString) ENABLED START
#	# TODO Uncomment and implement me.
	$(method toString,
		$(error $0(): NIY))
	# PROTECTED REGION END

	# PROTECTED REGION ID(MyFile_NumberOptionValue) ENABLED START
	$(if $(value 1),
		$(set value,$1))
	# PROTECTED REGION END
endef

#
# Model object 'OptionBinding'.
#
# The following features are defined:
#   - reference 'option'
#   - reference 'optionValue'
#
define class-MyOptionBinding
	# Extends 'EObject' class (implicitly).
	$(eobject MyFile_OptionBinding,
		MyOptionBinding,,)

	# Property 'option : MyOption'.
	# Property 'option_link : ELink'.
	$(eobject-reference MyFile_OptionBinding_option,
		option,MyOption,,changeable linkable)

	# Property 'optionValue : MyOptionValue'.
	$(eobject-reference MyFile_OptionBinding_optionValue,
		optionValue,MyOptionValue,,changeable containment)

	# PROTECTED REGION ID(MyFile_OptionBinding) ENABLED START
	$(method setOptionValue,
		$(for opt <- $(get option),
			$(if $(invoke opt->validate,$1),
				$(set-field optionValue,$1))))
	# PROTECTED REGION END
endef

# PROTECTED REGION ID(MyFile) ENABLED START
# TODO Add custom implementation here and remove this comment.
# PROTECTED REGION END

$(def_all)

endif # __mybuild_myfile_model_mk

