# Generated by Xpand using M2Make template.

# Model implementation of 'myFile' package.

ifndef __mybuild_myfile_model_impl_mk
__mybuild_myfile_model_impl_mk := $(lastword $(MAKEFILE_LIST))


# Implementation of 'Model' model object .
define class-ModelImpl
	$(super Model)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Model))

	$(field package : Package)
	$(method getPackage,
		$(get package))
	$(method setPackage,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Model_Package)))

	$(field imports : Import)
	$(method getImports,
		$(get imports))
	$(method setImports,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Model_Imports)))
	$(method addImports,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Model_Imports)))
	$(method removeImports,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Model_Imports)))
	$(method clearImports,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Model_Imports)))

	$(field entities : Entity)
	$(method getEntities,
		$(get entities))
	$(method setEntities,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Model_Entities)))
	$(method addEntities,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Model_Entities)))
	$(method removeEntities,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Model_Entities)))
	$(method clearEntities,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Model_Entities)))
endef

# Implementation of 'Package' model object .
define class-PackageImpl
	$(super Package)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Package))

	$(field name)
	$(method getName,
		$(get name))
	$(method setName,
		$(set name,$1))
endef

# Implementation of 'Import' model object .
define class-ImportImpl
	$(super Import)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Import))

	$(field importedNamespace)
	$(method getImportedNamespace,
		$(get importedNamespace))
	$(method setImportedNamespace,
		$(set importedNamespace,$1))
endef

# Implementation of 'Entity' model object .
define class-EntityImpl
	$(super Entity)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Entity))

	$(field name)
	$(method getName,
		$(get name))
	$(method setName,
		$(set name,$1))
endef

# Implementation of 'Interface' model object .
define class-InterfaceImpl
	$(super Interface)

	$(super NodeImpl)
	$(super Entity)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Interface))

	$(field superType : Interface)
	$(method getSuperType,
		$(get superType))
	$(method setSuperType,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Interface_SuperType)))

	$(field attributes : InterfaceProperty)
	$(method getAttributes,
		$(get attributes))
	$(method setAttributes,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Interface_Attributes)))
	$(method addAttributes,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Interface_Attributes)))
	$(method removeAttributes,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Interface_Attributes)))
	$(method clearAttributes,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Interface_Attributes)))
endef

define class-ReferenceToInterfaceImpl
	$(super ReferenceImpl,$(value 1))

	$(method getReferenceMetaClass,
		$(get myFileMetaModelInstance->Interface))
endef

# Implementation of 'InterfaceProperty' model object .
define class-InterfacePropertyImpl
	$(super InterfaceProperty)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->InterfaceProperty))
endef

# Implementation of 'Feature' model object .
define class-FeatureImpl
	$(super Feature)

	$(super NodeImpl)
	$(super InterfaceProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Feature))

	$(field name)
	$(method getName,
		$(get name))
	$(method setName,
		$(set name,$1))

	$(field superType : Feature)
	$(method getSuperType,
		$(get superType))
	$(method setSuperType,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Feature_SuperType)))
endef

define class-ReferenceToFeatureImpl
	$(super ReferenceImpl,$(value 1))

	$(method getReferenceMetaClass,
		$(get myFileMetaModelInstance->Feature))
endef

# Implementation of 'Module' model object .
define class-ModuleImpl
	$(super Module)

	$(super NodeImpl)
	$(super Entity)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Module))

	$(field static)
	$(method getStatic,
		$(get static))
	$(method setStatic,
		$(set static,$1))

	$(field abstract)
	$(method getAbstract,
		$(get abstract))
	$(method setAbstract,
		$(set abstract,$1))

	$(field superType : Module)
	$(method getSuperType,
		$(get superType))
	$(method setSuperType,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Module_SuperType)))

	$(field subTypes : Module)
	$(method getSubTypes,
		$(get subTypes))
	$(method setSubTypes,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Module_SubTypes)))
	$(method addSubTypes,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Module_SubTypes)))
	$(method removeSubTypes,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Module_SubTypes)))
	$(method clearSubTypes,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Module_SubTypes)))

	$(field attributes : ModuleProperty)
	$(method getAttributes,
		$(get attributes))
	$(method setAttributes,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Module_Attributes)))
	$(method addAttributes,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Module_Attributes)))
	$(method removeAttributes,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Module_Attributes)))
	$(method clearAttributes,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Module_Attributes)))

	$(field depends : Module)
	$(method getDepends,
		$(get depends))
	$(method setDepends,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Module_Depends)))
	$(method addDepends,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Module_Depends)))
	$(method removeDepends,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Module_Depends)))
	$(method clearDepends,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Module_Depends)))

	$(field dependent : Module)
	$(method getDependent,
		$(get dependent))
	$(method setDependent,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Module_Dependent)))
	$(method addDependent,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Module_Dependent)))
	$(method removeDependent,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Module_Dependent)))
	$(method clearDependent,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Module_Dependent)))
endef

define class-ReferenceToModuleImpl
	$(super ReferenceImpl,$(value 1))

	$(method getReferenceMetaClass,
		$(get myFileMetaModelInstance->Module))
endef

# Implementation of 'ModuleProperty' model object .
define class-ModulePropertyImpl
	$(super ModuleProperty)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->ModuleProperty))
endef

# Implementation of 'Depends' model object .
define class-DependsImpl
	$(super Depends)

	$(super NodeImpl)
	$(super ModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Depends))

	$(field modules : Module)
	$(method getModules,
		$(get modules))
	$(method setModules,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->Depends_Modules)))
	$(method addModules,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->Depends_Modules)))
	$(method removeModules,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->Depends_Modules)))
	$(method clearModules,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->Depends_Modules)))
endef

# Implementation of 'FeatureModuleProperty' model object .
define class-FeatureModulePropertyImpl
	$(super FeatureModuleProperty)

	$(super NodeImpl)
	$(super ModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->FeatureModuleProperty))

	$(field features : Feature)
	$(method getFeatures,
		$(get features))
	$(method setFeatures,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->FeatureModuleProperty_Features)))
	$(method addFeatures,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->FeatureModuleProperty_Features)))
	$(method removeFeatures,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->FeatureModuleProperty_Features)))
	$(method clearFeatures,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->FeatureModuleProperty_Features)))
endef

# Implementation of 'FilenameModuleProperty' model object .
define class-FilenameModulePropertyImpl
	$(super FilenameModuleProperty)

	$(super NodeImpl)
	$(super ModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->FilenameModuleProperty))

	$(field files : Filename)
	$(method getFiles,
		$(get files))
	$(method setFiles,
		$(invoke setNodeReference,$(get myFileMetaModelInstance->FilenameModuleProperty_Files)))
	$(method addFiles,
		$(invoke addNodeReference,$(get myFileMetaModelInstance->FilenameModuleProperty_Files)))
	$(method removeFiles,
		$(invoke removeNodeReference,$(get myFileMetaModelInstance->FilenameModuleProperty_Files)))
	$(method clearFiles,
		$(invoke clearNodeReference,$(get myFileMetaModelInstance->FilenameModuleProperty_Files)))
endef

# Implementation of 'Filename' model object .
define class-FilenameImpl
	$(super Filename)

	$(super NodeImpl)

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Filename))

	$(field name)
	$(method getName,
		$(get name))
	$(method setName,
		$(set name,$1))
endef

# Implementation of 'Requires' model object .
define class-RequiresImpl
	$(super Requires)

	$(super NodeImpl)
	$(super FeatureModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Requires))
endef

# Implementation of 'Provides' model object .
define class-ProvidesImpl
	$(super Provides)

	$(super NodeImpl)
	$(super FeatureModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Provides))
endef

# Implementation of 'Sources' model object .
define class-SourcesImpl
	$(super Sources)

	$(super NodeImpl)
	$(super FilenameModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Sources))
endef

# Implementation of 'Objects' model object .
define class-ObjectsImpl
	$(super Objects)

	$(super NodeImpl)
	$(super FilenameModuleProperty)Impl

	$(method getMetaClass,
		$(get myFileMetaModelInstance->Objects))
endef

$(def_all)

endif # __mybuild_myfile_model_impl_mk

