# Generated by Xpand using M2Make template.

# Factory for 'myFile' model.

ifndef __mybuild_myfile_factory_mk
__mybuild_myfile_factory_mk := $(lastword $(MAKEFILE_LIST))

include $(dir $(__mybuild_myfile_factory_mk))myfile-factory_impl.mk

# Provides methods for creating objects of 'myFile' model.
# See 'myFileFactoryInstance'.
define class-MyFileFactory
	$(super NodeFactory)

	# Creates a new 'Model' model object.
	$(method createModel)

	# Creates a new 'Package' model object.
	$(method createPackage)

	# Creates a new 'Import' model object.
	$(method createImport)

	# Creates a new 'Entity' model object.
	$(method createEntity)

	# Creates a new 'Interface' model object.
	$(method createInterface)
	# Creates a new reference to 'Interface'.
	#   1. Optional reference string to set initially.
	$(method createReferenceToInterface)

	# Creates a new 'Feature' model object.
	$(method createFeature)
	# Creates a new reference to 'Feature'.
	#   1. Optional reference string to set initially.
	$(method createReferenceToFeature)

	# Creates a new 'Module' model object.
	$(method createModule)
	# Creates a new reference to 'Module'.
	#   1. Optional reference string to set initially.
	$(method createReferenceToModule)

	# Creates a new 'Filename' model object.
	$(method createFilename)
endef

$(def_all)

myFileFactoryInstance := $(call new,MyFileFactoryImpl)

endif # __mybuild_myfile_factory_mk

