$_APIS += sched irq softirq

$_MODS                   += noirq
$_SRCS-pool_adapter      += noirq.c
$_PROVIDES-noirq  += irq

$_MODS                   += nosoftirq
$_SRCS-pool_adapter      += nosoftirq.c
$_PROVIDES-noirq  += softirq

$_MODS                   += nosched
$_SRCS-pool_adapter      += nosched.c
$_PROVIDES-noirq  += sched
