{PCI_VENDOR_ID_CIRRUS,  "Cirrus Logic"},
{PCI_VENDOR_ID_REALTEK, "Realtek Semiconductor Corp."},
{PCI_VENDOR_ID_RICOH,   "Ricoh Company, Ltd."},
{PCI_VENDOR_ID_ATHEROS, "Atheros Communications"},
{PCI_VENDOR_ID_RDC,     "RDC Semiconductor, Inc."},
{PCI_VENDOR_ID_INTEL,   "Intel Corporation"},
{PCI_VENDOR_ID_PLX,     "PLX Technology"},
{PCI_VENDOR_ID_BOCHS,   "Bochs Project"},
{PCI_VENDOR_ID_VIRTIO,  "VirtIO"}
