#!/bin/bash

if [ -f $EMBOX_GCC_ENV ]; then
	. $EMBOX_GCC_ENV
fi

case $EMBOX_GCC_LINK in
	full)
	       	ARG_LINE="$EMBOX_IMPORTED_CFLAGS $EMBOX_IMPORTED_LDFLAGS $EMBOX_IMPORTED_LDFLAGS_FULL"
		;;
	*)
	       	ARG_LINE="$EMBOX_IMPORTED_CFLAGS $EMBOX_IMPORTED_LDFLAGS -Wl,-r"
		;;
esac

case $@ in
	*-c*) ARG_LINE="$EMBOX_IMPORTED_CFLAGS";;
	*-E*) ARG_LINE=;;
esac

cmd=$(basename $0)
ARG_LINE="$@ $ARG_LINE $EMBOX_IMPORTED_CPPFLAGS"
#echo $EMBOX_CROSS_COMPILE${cmd#arch-embox-} $ARG_LINE
$EMBOX_CROSS_COMPILE${cmd#arch-embox-} $ARG_LINE
exit $?
