#
#   Date: Feb 9, 2012
# Author: Eldar Abusalimov
#

ifndef PERSIST_OBJECTS
$(error PERSIST_OBJECTS is not defined, nothing to serialize)
endif

ifndef mk_core_obj
$(error mk_core_obj is not defined, use the loader to run this script)
endif

.PHONY : all
all :
	@#

include $(filter-out $(MAKEFILE_LIST),$(mk_core_obj))

__persist_objects := $(PERSIST_OBJECTS)
override PERSIST_OBJECTS :=# Prevent expanding it once again.

ifdef PERSIST_REALLOC
__persist_realloc := $(PERSIST_REALLOC)
__persist_id_provider = .$(__persist_realloc)$(call alloc,$(__persist_realloc))
else
__persist_id_provider = $1
endif

$(info # Generated by GNU Make $(MAKE_VERSION) on $(shell date).)
$(info )
$(info $(\h) PERSIST_OBJECTS:)
$(foreach o,$(or $(__persist_objects),<nothing>),$(info $(\h)   $o))
$(info )
$(info $(call object_graph_print,$(__persist_objects),__persist_id_provider))
$(info )
