#!/usr/bin/env bash

# sudo modprobe vcan

sudo ip link add dev vcan0 type vcan
sudo ip link set up vcan0

./scripts/qemu/auto_qemu -object can-host-socketcan,id=canhost0,if=vcan0,canbus=canbus0 "$@"

sudo ip link set down vcan0
sudo ip link delete vcan0
