#!/bin/bash

QEMU=qemu-system-i386
#QEMU=qemu
IMAGE=../../build/base/bin/embox
#IMAGE=/home/user/workspace/downloads/zrv-qemu
EMBOX_MODS_CONF=../../conf/mods.config
SMP=" "

grep "include embox.kernel.smp" $EMBOX_MODS_CONF > /dev/null
if [ $? -eq 0 ]; then
SMP="-smp 2,cores=2"
break
fi

echo "$SMP"

whoami

sudo $QEMU -kernel $IMAGE -no-kvm \
$SMP \
-net nic,model=e1000,macaddr=AA:BB:CC:DD:EE:02 \
-net tap,ifname=tap0,script=start_script,downscript=stop_script \
-drive file="/dev/sda5",media=disk \
-drive file="/dev/mtdblock0",media=disk \
-drive file="./images/cd0.iso",media=cdrom \
-s -S $@
#-drive file="./images/zrv-mandatory.img",media=disk \

