#!/bin/bash

echo -ne "HTTP/1.1 200 OK\r\n"
echo -ne "Content-Type: application/json\r\n"
echo -ne "Connection: close\r\n"
echo -ne "\r\n"

if [ $REQUEST_METHOD = "GET" ]; then
	echo "Query: $QUERY_STRING" >&2
	STATES="0, 1"
	echo [ $(printf "${STATES}, %.0s" {1..39}) $STATES ]
elif [ $REQUEST_METHOD = "POST" ]; then
	read -n $CONTENT_LENGTH POST_DATA
	echo "Posted: $POST_DATA" >&2
fi
