$_PACKAGE := embox.driver.interrupts

$_MODS += mb_interrupt at91_interrupt apic_interrupt

$_SRCS-mb_interrupt += mb_interrupt.c

$_SRCS-at91_interrupt += at91_interrupt.c

$_SRCS-apic_interrupt += apic_interrupt.c

