$_PACKAGE := embox.driver.interrupts

$_MODS += mb at91 apic

$_PROVIDES-mb   += embox.hal.interrupt
$_SRCS-mb       += mb.c

$_PROVIDES-at91 += embox.hal.interrupt
$_SRCS-at91     += at91.c

$_PROVIDES-apic += embox.hal.interrupt
$_SRCS-apic     += apic.c

