#include <hal/reg.h>

#include <drivers/at91sam7s256.h>

void hardware_init_hook(void) {
	REG_STORE(AT91C_CKGR_MOR, AT91C_CKGR_MOSCEN | 6 << 8 );
	while (! (REG_LOAD(AT91C_PMC_SR) | AT91C_PMC_MOSCS));

	REG_STORE(AT91C_CKGR_PLLR, (CONFIG_SYS_CLK_MUL << AT91C_CKGR_MUL_OFFSET) | \
							   (CONFIG_SYS_CLK_DIV << AT91C_CKGR_DIV_OFFSET) | \
							   (0x1c << AT91C_CKGR_PLLCOUNT_OFFSET));
	while (! (REG_LOAD(AT91C_PMC_SR) | AT91C_PMC_LOCK));

	REG_STORE(AT91C_PMC_MCKR, AT91C_PMC_PRES_CLK_2);
	while (! (REG_LOAD(AT91C_PMC_SR) | AT91C_PMC_MCKRDY));

	REG_STORE(AT91C_PMC_MCKR, AT91C_PMC_CSS_PLL_CLK | AT91C_PMC_PRES_CLK_2);
	while (! (REG_LOAD(AT91C_PMC_SR) | AT91C_PMC_MCKRDY));
}
