/**
 * @file
 * @brief
 *
 * @author  Anton Bondarev
 * @date    03.07.2026
 */

#include <util/log.h>

#include <assert.h>

#include <drivers/gpio.h>

#include <framework/mod/options.h>
#include <util/macro.h>
#include <config/board_config.h>

#include "k1921vg1t_udc_priv.h"


#define USB_NUM               OPTION_GET(NUMBER, usb_num)


#define CONF_PIN_PREF         MACRO_CONCAT(MACRO_CONCAT(CONF_USB,USB_NUM),_PIN_)

#define USB_PORT(name) \
			MACRO_CONCAT(MACRO_CONCAT(CONF_PIN_PREF, name), _PORT)
#define USB_PIN(name) \
			MACRO_CONCAT(MACRO_CONCAT(CONF_PIN_PREF, name), _NR)
#define USB_AF(name)  \
			MACRO_CONCAT(MACRO_CONCAT(CONF_PIN_PREF, name), _AF)

void usb_phy_utmi_bconf_init(void) {
	/* CLK */
	gpio_setup_mode(USB_PORT(CLK), (1 << USB_PIN(CLK)),
	    GPIO_MODE_ALT_SET(USB_AF(CLK)) | GPIO_MODE_OUT_PUSH_PULL);

	/* D0 */
	gpio_setup_mode(USB_PORT(D0), (1 << USB_PIN(D0)),
	    GPIO_MODE_ALT_SET(USB_AF(D0)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D1 */
	gpio_setup_mode(USB_PORT(D1), (1 << USB_PIN(D1)),
	    GPIO_MODE_ALT_SET(USB_AF(D1)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D2 */
	gpio_setup_mode(USB_PORT(D2), (1 << USB_PIN(D2)),
	    GPIO_MODE_ALT_SET(USB_AF(D2)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D3 */
	gpio_setup_mode(USB_PORT(D3), (1 << USB_PIN(D3)),
	    GPIO_MODE_ALT_SET(USB_AF(D3)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D4 */
	gpio_setup_mode(USB_PORT(D4), (1 << USB_PIN(D4)),
	    GPIO_MODE_ALT_SET(USB_AF(D4)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D5 */
	gpio_setup_mode(USB_PORT(D5), (1 << USB_PIN(D5)),
	    GPIO_MODE_ALT_SET(USB_AF(D5)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D6 */
	gpio_setup_mode(USB_PORT(D6), (1 << USB_PIN(D6)),
	    GPIO_MODE_ALT_SET(USB_AF(D6)) | GPIO_MODE_OUT_PUSH_PULL);
	/* D7 */
	gpio_setup_mode(USB_PORT(D7), (1 << USB_PIN(D7)),
	    GPIO_MODE_ALT_SET(USB_AF(D7)) | GPIO_MODE_OUT_PUSH_PULL);

	/* HOSTDISCONNECT */
	gpio_setup_mode(USB_PORT(HOSTDISCONNECT), (1 << USB_PIN(HOSTDISCONNECT)),
	    GPIO_MODE_ALT_SET(USB_AF(HOSTDISCONNECT)) | GPIO_MODE_OUT_PUSH_PULL);

	/* IDPULLUP */
	gpio_setup_mode(USB_PORT(IDPULLUP), (1 << USB_PIN(IDPULLUP)),
	    GPIO_MODE_ALT_SET(USB_AF(IDPULLUP)) | GPIO_MODE_OUT_PUSH_PULL);

	/* VBUSVALID */
	gpio_setup_mode(USB_PORT(VBUSVALID), (1 << USB_PIN(VBUSVALID)),
	    GPIO_MODE_ALT_SET(USB_AF(VBUSVALID)) | GPIO_MODE_OUT_PUSH_PULL);

	/* RXERROR */
	gpio_setup_mode(USB_PORT(RXERROR), (1 << USB_PIN(RXERROR)),
	    GPIO_MODE_ALT_SET(USB_AF(RXERROR)) | GPIO_MODE_OUT_PUSH_PULL);

	/* RXVALID */
	gpio_setup_mode(USB_PORT(RXVALID), (1 << USB_PIN(RXVALID)),
	    GPIO_MODE_ALT_SET(USB_AF(RXVALID)) | GPIO_MODE_OUT_PUSH_PULL);

	/* RXVALID */
	gpio_setup_mode(USB_PORT(RXVALID), (1 << USB_PIN(RXVALID)),
	    GPIO_MODE_ALT_SET(USB_AF(RXVALID)) | GPIO_MODE_OUT_PUSH_PULL);

	/* TXREADY */
	gpio_setup_mode(USB_PORT(TXREADY), (1 << USB_PIN(TXREADY)),
	    GPIO_MODE_ALT_SET(USB_AF(TXREADY)) | GPIO_MODE_OUT_PUSH_PULL);

	/* TXVALID */
	gpio_setup_mode(USB_PORT(TXVALID), (1 << USB_PIN(TXVALID)),
	    GPIO_MODE_ALT_SET(USB_AF(TXVALID)) | GPIO_MODE_OUT_PUSH_PULL);

	/* LINESTATE1 */
	gpio_setup_mode(USB_PORT(LINESTATE1), (1 << USB_PIN(LINESTATE1)),
	    GPIO_MODE_ALT_SET(USB_AF(LINESTATE1)) | GPIO_MODE_OUT_PUSH_PULL);

	/* LINESTATE0 */
	gpio_setup_mode(USB_PORT(LINESTATE0), (1 << USB_PIN(LINESTATE0)),
	    GPIO_MODE_ALT_SET(USB_AF(LINESTATE0)) | GPIO_MODE_OUT_PUSH_PULL);

	/* OPMODE1 */
	gpio_setup_mode(USB_PORT(OPMODE1), (1 << USB_PIN(OPMODE1)),
	    GPIO_MODE_ALT_SET(USB_AF(OPMODE1)) | GPIO_MODE_OUT_PUSH_PULL);

	/* LINESTATE0 */
	gpio_setup_mode(USB_PORT(OPMODE0), (1 << USB_PIN(OPMODE0)),
	    GPIO_MODE_ALT_SET(USB_AF(OPMODE0)) | GPIO_MODE_OUT_PUSH_PULL);

	/* SUSPENDM */
	gpio_setup_mode(USB_PORT(SUSPENDM), (1 << USB_PIN(SUSPENDM)),
	    GPIO_MODE_ALT_SET(USB_AF(SUSPENDM)) | GPIO_MODE_OUT_PUSH_PULL);

	/* TERMSELECT */
	gpio_setup_mode(USB_PORT(TERMSELECT), (1 << USB_PIN(TERMSELECT)),
	    GPIO_MODE_ALT_SET(USB_AF(TERMSELECT)) | GPIO_MODE_OUT_PUSH_PULL);

	/* XCVRSELECT1 */
	gpio_setup_mode(USB_PORT(XCVRSELECT1), (1 << USB_PIN(XCVRSELECT1)),
	    GPIO_MODE_ALT_SET(USB_AF(XCVRSELECT1)) | GPIO_MODE_OUT_PUSH_PULL);

	/* LINESTATE0 */
	gpio_setup_mode(USB_PORT(XCVRSELECT0), (1 << USB_PIN(XCVRSELECT0)),
	    GPIO_MODE_ALT_SET(USB_AF(XCVRSELECT0)) | GPIO_MODE_OUT_PUSH_PULL);

	/* LINESTATE0 */
	gpio_setup_mode(USB_PORT(RESET), (1 << USB_PIN(RESET)),
	    GPIO_MODE_ALT_SET(USB_AF(RESET)) | GPIO_MODE_OUT_PUSH_PULL);
}