#!/usr/bin/expect

source exec_through_telnet.exp

set embox_ip [lindex $argv 0]
set host_ip  [lindex $argv 1]

proc ping_test {} {
	global host_ip
	send "ping -c 1 $host_ip\r\n"
	expect {
	        timeout  { puts "ping.exp: timeout\n"; return -1 }
	        "+0 errors"
	}
	return 0
}

if {$embox_ip == "" || $host_ip == ""} {
	puts "Usage: ping.exp <embox_ip> <host_ip>\n"
	exit 1
}

exec_cmd "$embox_ip" ping_test
