#!/usr/bin/expect

source [file join [file dirname [info script]] framework/test_core.exp]

namespace import autotest::*

TEST_CASE_TARGET {Embox should ping host} {
	variable host_ip

	send "ping -c 4 $host_ip\r"
	test_assert_regexp_equal "0 errors"

	return 0
}

TEST_CASE_TARGET {Embox should ping google.com} {
	variable host_ip

	send "ping -c 4 google.com\r"
	test_assert_regexp_equal "0 errors"

	return 0
}
