#!/usr/bin/runtest

source test_cmd.exp
source exec_through_telnet.exp

proc vfat_test {} {
	global host_ip
	send "mkdir /vfat_mnt\r"
	expect ":/#"

	send "umount /vfat_mnt\r"
	expect ":/#"

	test_assert_ok "mkfs -t vfat /dev/hda\r" ":/#"

	test_assert_ok "mount -t vfat /dev/hda /vfat_mnt\r" ":/#"

	test_assert_ok "touch /vfat_mnt/f1.txt\r" ":/#"

	test_assert_ok "ls /vfat_mnt\r" "/vfat_mnt/f1.txt"

	test_assert_ok "umount /vfat_mnt\r" ":/#"

	return 0
}

exec_cmd "$embox_ip" vfat_test
