$_MODS += touch_sensor
$_SRCS-touch_sensor += touch.c
$_DEPS-touch_sensor += nxt_avr_init

$_MODS += sonar_sensor
$_SRCS-sonar_sensor += sonar.c
$_DEPS-sonar_sensor += soft_i2c

$_MODS += angle_sensor
$_SRCS-sonar_sensor += angle.c
$_DEPS-sonar_sensor += soft_i2c
