
$_MODS += threads_big threads_show threads_delete threads_recursion threads_heap

$_SRCS-threads_big += *threads_big.c
$_SRCS-threads_show += *threads_show.c
$_SRCS-threads_delete += *threads_delete.c
$_SRCS-threads_recursion += *threads_recursion.c
$_SRCS-threads_heap += *threads_heap.c
