
$_MODS += threads_mutex threads_lock threads_big threads_show threads_delete
$_MODS += threads_recursion threads_priority threads_msg

$_SRCS-threads_big += *threads_big.c
$_SRCS-threads_show += *threads_show.c
$_SRCS-threads_delete += *threads_delete.c
$_SRCS-threads_recursion += *threads_recursion.c
$_SRCS-threads_priority += *threads_priority.c
$_SRCS-threads_msg += *threads_msg.c
$_SRCS-threads_lock += *threads_lock.c
$_SRCS-threads_mutex += *threads_mutex.c
