
$_MODS += threads_big threads_yield threads_delete threads_recursion threads_heap

$_SRCS-threads_big += *threads_big.c
$_SRCS-threads_yield += *threads_yield.c
$_SRCS-threads_delete += *threads_delete.c
$_SRCS-threads_recursion += *threads_recursion.c
$_SRCS-threads_heap += *threads_heap.c
