$_PACKAGE := embox.test.mem

$_MODS         += objalloc
$_SRCS-objalloc+= objalloc.c
$_REQUIRES-objalloc += embox.mem.objalloc

$_MODS += heap
$_SRCS-heap += heap.c
$_REQUIRES-heap += embox.mem.heap_api

$_MODS += page
$_SRCS-page += page.c
$_REQUIRES-page += embox.mem.page_api
