/**
 * @file
 * @brief
 *
 * @date 10.10.2012
 * @author Anton Bulychev
 */

//#include <kernel/syscall.h>

#include <types.h>

#define SYSCALL_NRS_TOTAL 200

extern void *sys_mmap2(void *start, size_t length, int prot, int flags, int fd, uint32_t pgoffset);

void *const SYSCALL_TABLE[SYSCALL_NRS_TOTAL] = {
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 0 - 9
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 10 - 19
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 20 - 29
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 30 - 39
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 40 - 49
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 50
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 60
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 70
 	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 80
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 90
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 100
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 110
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 120
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 130
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 140
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 150
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 160
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 170
	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 180
	NULL, NULL, sys_mmap2, NULL, NULL, NULL, NULL, NULL, NULL, NULL,    // 190
};
