$_MODS                 += at91_timer_test
$_SRCS-at91_timer_test += at91_timer.c
$_DEPS-at91_timer_test += embox.driver.clock.at91_pitc
$_DEPS-at91_timer_test += $(PLATFORM).driver.at91_olimex_debug_led
