
$_CPPFLAGS += -I$($_PLATFORM)/include
$_MODS += at91_timer_test
$_SRCS-at91_timer_test += test.c
$_DEPS-at91_timer_test += embox.driver.timers.at91_timer
$_DEPS-at91_timer_test += $(PLATFORM).driver.at91_olimex_debug_led
