
$_MODS += mmu_enable mmu_rw

$_SRCS-mmu_enable += mmu_enable.c
$_SRCS-mmu_rw += mmu_rw.c

$_DEPS-mmu_enable += embox.hal.test.mmu
$_DEPS-mmu_enable += embox.hal.mm.mmu
$_DEPS-mmu_rw += embox.hal.test.mmu
$_DEPS-mmu_rw += embox.hal.mm.mmu
