#!/bin/bash

LOCK=qemu.lck

while [ -f $LOCK ]; do
	sudo qemu -s -S -kernel build/base/bin/embox \
	-net nic,model=ne2k_pci,macaddr=AA:BB:CC:DD:EE:02 \
	-net tap,name=tap0,script=start_script,downscript=stop_script -nographic \
	$@
done
