#!/usr/bin/env bash

SYSLINUX_ROOT=$(dirname $0)/syslinux
EXTLINUX=${SYSLINUX_ROOT}/sbin/extlinux
SYSLINUX_SHARE=${SYSLINUX_ROOT}/usr/share/syslinux

EMBOX_MULTIBOOT=./build/base/bin/embox

MOUNT_POINT=/media/embox-live

DATA_DIR=$(dirname $0)/bootloader_cfgs

usage() {
	echo "Make live usb."
	echo
	echo "Usage:"
	echo "    $0 <type> <device>"
	echo
	echo "<type> is bootloader type: grub (for grub v1.0), grub2 or syslinux"
	echo "<device> is dev file of flash."
	echo
	echo "Example:"
	echo "    $0 grub /dev/sdb"
}

grub1_do () {
	DRIVE=$1
	grub-install --root-directory=$MOUNT_POINT $DRIVE

	cp $DATA_DIR/grub1-config $MOUNT_POINT/boot/grub/menu.lst

}

grub2_do () {
	DRIVE=$1
	grub-install --root-directory=$MOUNT_POINT $DRIVE

	cp $DATA_DIR/grub2-config $MOUNT_POINT/boot/grub/grub.cfg

}

syslinux_do() {
	DRIVE=$1
	MP=$2
	SYSLINUX_DIR=$MP/boot/syslinux

	[ -d $SYSLINUX_DIR ] || mkdir -p $SYSLINUX_DIR

	$EXTLINUX -i $SYSLINUX_DIR

	dd if=${SYSLINUX_ROOT}/usr/share/syslinux/mbr.bin of=$DRIVE

	cp $SYSLINUX_SHARE/{libcom32,mboot}.c32 $SYSLINUX_DIR/

	cp $DATA_DIR/syslinux-config $MP/boot/syslinux/syslinux.cfg

}

if [ ! $# = 2 ]; then
	usage
	exit 1
fi

DRIVE=$2
PARTITION=${DRIVE}1
[ -d $MOUNT_POINT ] || mkdir $MOUNT_POINT
umount $PARTITION

if [ -z $LIVEFLASH_CPONLY ]; then
	dd if=/dev/zero of=$DRIVE bs=512 count=1
	if [ ! -b $DRIVE ]; then
		# default values (as seems to QEMU)
		SECTOR_SIZE=512
		SECTOR_TRACK=63
		HEAD_N=16

		# cylinder_n depends from image size
		CYLINDER_N=$(( `stat -c %s $DRIVE` / \
			($SECTOR_SIZE * $SECTOR_TRACK * $HEAD_N) ))

		PARTITION_OFFSET_CYLINDERS=60

		echo "$PARTITION_OFFSET_CYLINDERS,,L,*" | \
			sfdisk -H $HEAD_N -C $CYLINDER_N -S $SECTOR_TRACK $DRIVE
		PARTITION=`losetup -f`
		losetup -o $(( $PARTITION_OFFSET_CYLINDERS \
				* $SECTOR_TRACK \
				* $HEAD_N \
				* $SECTOR_SIZE )) \
			$PARTITION $DRIVE
	else
		echo "60,,L,*" | sfdisk $DRIVE

	fi
	MKE2FS_DEVICE_SECTSIZE=512 mke2fs $PARTITION -b 1024 -v
fi

mount $PARTITION $MOUNT_POINT

if [ -z $LIVEFLASH_CPONLY ]; then
	if [ z"$1" == zgrub ]; then
		grub1_do $DRIVE $MOUNT_POINT
	elif [ z"$1" == zgrub2 ]; then
		grub2_do $DRIVE $MOUNT_POINT
	elif [ z"$1" == zsyslinux ]; then
		syslinux_do $DRIVE $MOUNT_POINT

	else
		echo Unknown bootloader type
		exit 1
	fi
fi

cp $EMBOX_MULTIBOOT $MOUNT_POINT/boot/embox

umount $MOUNT_POINT
rmdir $MOUNT_POINT

if [ ! -b $DRIVE ]; then
	losetup -d $PARTITION
fi
