#!/bin/sh

BUILDBOT="/usr/bin/env buildbot"

# user specific
TRYWHO=nobody

# buildmaster specific
MASTER=twister:8031
USER=trybuild
PASSWD=trybuild

# project specific
CONNECT=pb
VC=svn

# end of params

if [ -z $TOPDIR ]; then
	TOPDIR=$PWD
fi

$BUILDBOT try --connect=$CONNECT --master=$MASTER --user=$USER --passwd=$PASSWD \
	--vc=$VC --topdir=$TOPDIR --who=$TRYWHO "$@"
