/* 8 LEDS stm32f3-discovery */
{ .gpio = GPIO_PORT_E, .pin = (1 << 9) }, /* 0 LED3 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 10) }, /* 2 LED5 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 11) }, /* 4 LED7 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 12) }, /* 6 LED9 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 13) }, /* 7 LED10 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 14) }, /* 5 LED8 */
{ .gpio = GPIO_PORT_E, .pin = (1 << 15) },  /* 3 LED6 */ 
{ .gpio = GPIO_PORT_E, .pin = (1 << 8) },  /* 2 LED4 */


