$_MODS_CORE += locore

$_SRCS-locore += head.S
$_SRCS-locore += sys.c
$_SRCS-locore += traps.c

$_SRCS-locore += entry.S trap_*.S winflush.S

$_SRCS-arch      += arch.c
$_SRCS-context   += context.c context_switch.S
