
ifdef CONFIG_AMBAPP
$_MODS += ambapp amba_regitry
$_SRCS-ambapp += ambapp.c
$_SRCS-amba_regitry += amba_registry.c
$_DEPS-amba_regitry += ambapp
$_CPPFLAGS-amba_regitry +=-I$(SRC_DIR)/drivers/ambapp
endif
