$_PACKAGE := embox.driver.serial

$_MODS += xuartlite

$_SRCS-xuartlite += serial_xuartlite.c

$_MODS += at91_uart

$_SRCS-at91_uart += at91_uart.c

$_MODS += skyeye_uart

$_SRCS-skyeye_uart += skyeye_uart.c
