
#ifndef MDR1206FI_RST_CLK_H
#define MDR1206FI_RST_CLK_H

#include <stdint.h>


#define RST_CLK_CLOCK_STATUS_PLL_CPU_RDY_Pos 1
#define RST_CLK_CLOCK_STATUS_PLL_CPU_RDY_Msk (0x1UL << RST_CLK_CLOCK_STATUS_PLL_CPU_RDY_Pos)
#define RST_CLK_CLOCK_STATUS_PLL_CPU_RDY     RST_CLK_CLOCK_STATUS_PLL_CPU_RDY_Msk

#define RST_CLK_CLOCK_STATUS_HSE_RDY_Pos     2
#define RST_CLK_CLOCK_STATUS_HSE_RDY_Msk     (0x1UL << RST_CLK_CLOCK_STATUS_HSE_RDY_Pos)
#define RST_CLK_CLOCK_STATUS_HSE_RDY         RST_CLK_CLOCK_STATUS_HSE_RDY_Msk



#define RST_CLK_PLL_CONTROL_PLL_CPU_ON_Pos  2
#define RST_CLK_PLL_CONTROL_PLL_CPU_ON_Msk  (0x1UL << RST_CLK_PLL_CONTROL_PLL_CPU_ON_Pos)
#define RST_CLK_PLL_CONTROL_PLL_CPU_ON      RST_CLK_PLL_CONTROL_PLL_CPU_ON_Msk

#define RST_CLK_PLL_CONTROL_PLL_CPU_SEL_Pos 3
#define RST_CLK_PLL_CONTROL_PLL_CPU_SEL_Msk (0x1UL << RST_CLK_PLL_CONTROL_PLL_CPU_SEL_Pos)
#define RST_CLK_PLL_CONTROL_PLL_CPU_SEL     RST_CLK_PLL_CONTROL_PLL_CPU_SEL_Msk


#define RST_CLK_PLL_CONTROL_PLL_CPU_MUL_Pos 8
#define RST_CLK_PLL_CONTROL_PLL_CPU_MUL_Msk (0x7UL << RST_CLK_PLL_CONTROL_PLL_CPU_MUL_Pos)


#define RST_CLK_HS_CONTROL_HSE_ON_Pos  0
#define RST_CLK_HS_CONTROL_HSE_ON_Msk  (0x1UL << RST_CLK_HS_CONTROL_HSE_ON_Pos)
#define RST_CLK_HS_CONTROL_HSE_ON      RST_CLK_HS_CONTROL_HSE_ON_Msk

#define RST_CLK_HS_CONTROL_HSE_BYP_Pos 1
#define RST_CLK_HS_CONTROL_HSE_BYP_Msk (0x1UL << RST_CLK_HS_CONTROL_HSE_BYP_Pos)
#define RST_CLK_HS_CONTROL_HSE_BYP     RST_CLK_HS_CONTROL_HSE_BYP_Msk



#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos       0
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_Msk       (0x3UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI       (0x0UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI_DIV_2 (0x1UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE       (0x2UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE_DIV_2 (0x3UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)


#define RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos       2
#define RST_CLK_CPU_CLOCK_CPU_C2_SEL_Msk       (0x1UL << RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C2_SEL           RST_CLK_CPU_CLOCK_CPU_C2_SEL_Msk

#define RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos       4
#define RST_CLK_CPU_CLOCK_CPU_C3_SEL_Msk       (0xFUL << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos)

#define RST_CLK_CPU_CLOCK_HCLK_SEL_Pos         8
#define RST_CLK_CPU_CLOCK_HCLK_SEL_Msk         (0x3UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_HSI         (0x0UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_CPU_C3      (0x1UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_LSE         (0x2UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_LSI         (0x3UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)


#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos        0
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_Msk        (0x3UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSI        (0x0UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSI_DIV_2  (0x1UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSE        (0x2UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSE_DIV_2  (0x3UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)

#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos        2
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_Msk        (0x3UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_CPU_C1     (0x0UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_PER1_C1    (0x1UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_PLLCPU     (0x2UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_HSI_C1_CLK (0x3UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)

#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Pos     4
#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Msk     (0x1UL << RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Pos)
#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG         RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Msk

#define RST_CLK_PER1_CLOCK_DMA_EN_Pos             5
#define RST_CLK_PER1_CLOCK_DMA_EN_Msk             (0x1UL << RST_CLK_PER1_CLOCK_DMA_EN_Pos)
#define RST_CLK_PER1_CLOCK_DMA_EN                 RST_CLK_PER1_CLOCK_DMA_EN_Msk

#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos         6
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_Msk         (0x3UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSI         (0x0UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSI_DIV_2   (0x1UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSE         (0x2UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSE_DIV_2   (0x3UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)

#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos         8
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_Msk         (0x3UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_CPU_C1      (0x0UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_PER1_C1     (0x1UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_PLLCPU      (0x2UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_HSI_C1_CLK  (0x3UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)

#define RST_CLK_PER1_CLOCK_WDG_BRG_Pos            10
#define RST_CLK_PER1_CLOCK_WDG_BRG_Msk            (0x7UL << RST_CLK_PER1_CLOCK_WDG_BRG_Pos)

#define RST_CLK_PER1_CLOCK_WDG_CLK_EN_Pos         13
#define RST_CLK_PER1_CLOCK_WDG_CLK_EN_Msk         (0x1UL << RST_CLK_PER1_CLOCK_WDG_CLK_EN_Pos)
#define RST_CLK_PER1_CLOCK_WDG_CLK_EN             RST_CLK_PER1_CLOCK_WDG_CLK_EN_Msk




#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos          0
#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_Msk          (0x3UL << RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_CPU_C1       (0x0UL << RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_PER1_C1      (0x1UL << RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_PLLCPU       (0x2UL << RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADC_C1_SEL_HSE_C1_CLK   (0x3UL << RST_CLK_ADC_CLOCK_ADC_C1_SEL_Pos)

#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos        2
#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Msk        (0x3UL << RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_CPU_C1     (0x0UL << RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_PER1_C1    (0x1UL << RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_PLLCPU     (0x2UL << RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos)
#define RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_HSE_C1_CLK (0x3UL << RST_CLK_ADC_CLOCK_ADCUI_C1_SEL_Pos)

#define RST_CLK_ADC_CLOCK_ADCUI_C3_SEL_Pos        4
#define RST_CLK_ADC_CLOCK_ADCUI_C3_SEL_Msk        (0xFUL << RST_CLK_ADC_CLOCK_ADCUI_C3_SEL_Pos)

#define RST_CLK_ADC_CLOCK_ADC_C3_SEL_Pos          8
#define RST_CLK_ADC_CLOCK_ADC_C3_SEL_Msk          (0xFUL << RST_CLK_ADC_CLOCK_ADC_C3_SEL_Pos)

#define RST_CLK_ADC_CLOCK_ADCUI_CLK_EN_Pos        12
#define RST_CLK_ADC_CLOCK_ADCUI_CLK_EN_Msk        (0x1UL << RST_CLK_ADC_CLOCK_ADCUI_CLK_EN_Pos)
#define RST_CLK_ADC_CLOCK_ADCUI_CLK_EN            RST_CLK_ADC_CLOCK_ADCUI_CLK_EN_Msk

#define RST_CLK_ADC_CLOCK_ADC_CLK_EN_Pos          13
#define RST_CLK_ADC_CLOCK_ADC_CLK_EN_Msk          (0x1UL << RST_CLK_ADC_CLOCK_ADC_CLK_EN_Pos)
#define RST_CLK_ADC_CLOCK_ADC_CLK_EN              RST_CLK_ADC_CLOCK_ADC_CLK_EN_Msk



#define RST_CLK_RTC_CLOCK_HSE_SEL_Pos    0
#define RST_CLK_RTC_CLOCK_HSE_SEL_Msk    (0xFUL << RST_CLK_RTC_CLOCK_HSE_SEL_Pos)

#define RST_CLK_RTC_CLOCK_HSI_SEL_Pos    4
#define RST_CLK_RTC_CLOCK_HSI_SEL_Msk    (0xFUL << RST_CLK_RTC_CLOCK_HSI_SEL_Pos)

#define RST_CLK_RTC_CLOCK_HSE_RTC_EN_Pos 8
#define RST_CLK_RTC_CLOCK_HSE_RTC_EN_Msk (0x1UL << RST_CLK_RTC_CLOCK_HSE_RTC_EN_Pos)
#define RST_CLK_RTC_CLOCK_HSE_RTC_EN     RST_CLK_RTC_CLOCK_HSE_RTC_EN_Msk

#define RST_CLK_RTC_CLOCK_HSI_RTC_EN_Pos 9
#define RST_CLK_RTC_CLOCK_HSI_RTC_EN_Msk (0x1UL << RST_CLK_RTC_CLOCK_HSI_RTC_EN_Pos)
#define RST_CLK_RTC_CLOCK_HSI_RTC_EN     RST_CLK_RTC_CLOCK_HSI_RTC_EN_Msk


#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP1_Pos    0
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP1_Msk    (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_SSP1_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP1        RST_CLK_PER2_CLOCK_PCLK_EN_SSP1_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_UART1_Pos   1
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART1_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_UART1_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART1       RST_CLK_PER2_CLOCK_PCLK_EN_UART1_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_UART2_Pos   2
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART2_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_UART2_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART2       RST_CLK_PER2_CLOCK_PCLK_EN_UART2_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_FLASH_Pos   3
#define RST_CLK_PER2_CLOCK_PCLK_EN_FLASH_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_FLASH_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_FLASH       RST_CLK_PER2_CLOCK_PCLK_EN_FLASH_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_RST_CLK_Pos 4
#define RST_CLK_PER2_CLOCK_PCLK_EN_RST_CLK_Msk (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_RST_CLK_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_RST_CLK     RST_CLK_PER2_CLOCK_PCLK_EN_RST_CLK_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_DMA_Pos     5
#define RST_CLK_PER2_CLOCK_PCLK_EN_DMA_Msk     (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_DMA_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_DMA         RST_CLK_PER2_CLOCK_PCLK_EN_DMA_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_I2C_Pos     6
#define RST_CLK_PER2_CLOCK_PCLK_EN_I2C_Msk     (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_I2C_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_I2C         RST_CLK_PER2_CLOCK_PCLK_EN_I2C_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_UART3_Pos   7
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART3_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_UART3_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART3       RST_CLK_PER2_CLOCK_PCLK_EN_UART3_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_ADC_Pos     8
#define RST_CLK_PER2_CLOCK_PCLK_EN_ADC_Msk     (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_ADC_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_ADC         RST_CLK_PER2_CLOCK_PCLK_EN_ADC_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_WWDG_Pos    9
#define RST_CLK_PER2_CLOCK_PCLK_EN_WWDG_Msk    (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_WWDG_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_WWDG        RST_CLK_PER2_CLOCK_PCLK_EN_WWDG_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_IWDG_Pos    10
#define RST_CLK_PER2_CLOCK_PCLK_EN_IWDG_Msk    (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_IWDG_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_IWDG        RST_CLK_PER2_CLOCK_PCLK_EN_IWDG_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_POWER_Pos   11
#define RST_CLK_PER2_CLOCK_PCLK_EN_POWER_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_POWER_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_POWER       RST_CLK_PER2_CLOCK_PCLK_EN_POWER_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_BKP_Pos     12
#define RST_CLK_PER2_CLOCK_PCLK_EN_BKP_Msk     (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_BKP_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_BKP         RST_CLK_PER2_CLOCK_PCLK_EN_BKP_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_ADCUI_Pos   13
#define RST_CLK_PER2_CLOCK_PCLK_EN_ADCUI_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_ADCUI_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_ADCUI       RST_CLK_PER2_CLOCK_PCLK_EN_ADCUI_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER1_Pos  14
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER1_Msk  (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_TIMER1_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER1      RST_CLK_PER2_CLOCK_PCLK_EN_TIMER1_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER2_Pos  15
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER2_Msk  (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_TIMER2_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER2      RST_CLK_PER2_CLOCK_PCLK_EN_TIMER2_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTA_Pos   16
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTA_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_PORTA_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTA       RST_CLK_PER2_CLOCK_PCLK_EN_PORTA_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTB_Pos   17
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTB_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_PORTB_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTB       RST_CLK_PER2_CLOCK_PCLK_EN_PORTB_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTC_Pos   18
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTC_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_PORTC_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTC       RST_CLK_PER2_CLOCK_PCLK_EN_PORTC_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_CRC_Pos     19
#define RST_CLK_PER2_CLOCK_PCLK_EN_CRC_Msk     (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_CRC_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_CRC         RST_CLK_PER2_CLOCK_PCLK_EN_CRC_Msk


#define RST_CLK_PER2_CLOCK_PCLK_EN_RANDOM_Pos  23
#define RST_CLK_PER2_CLOCK_PCLK_EN_RANDOM_Msk  (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_RANDOM_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_RANDOM      RST_CLK_PER2_CLOCK_PCLK_EN_RANDOM_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_ISO7816_Pos 24
#define RST_CLK_PER2_CLOCK_PCLK_EN_ISO7816_Msk (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_ISO7816_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_ISO7816     RST_CLK_PER2_CLOCK_PCLK_EN_ISO7816_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP2_Pos    25
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP2_Msk    (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_SSP2_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP2        RST_CLK_PER2_CLOCK_PCLK_EN_SSP2_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP3_Pos    26
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP3_Msk    (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_SSP3_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_SSP3        RST_CLK_PER2_CLOCK_PCLK_EN_SSP3_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER3_Pos  27
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER3_Msk  (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_TIMER3_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER3      RST_CLK_PER2_CLOCK_PCLK_EN_TIMER3_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER4_Pos  28
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER4_Msk  (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_TIMER4_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_TIMER4      RST_CLK_PER2_CLOCK_PCLK_EN_TIMER4_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_UART4_Pos   29
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART4_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_UART4_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_UART4       RST_CLK_PER2_CLOCK_PCLK_EN_UART4_Msk

#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTD_Pos   30
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTD_Msk   (0x1UL << RST_CLK_PER2_CLOCK_PCLK_EN_PORTD_Pos)
#define RST_CLK_PER2_CLOCK_PCLK_EN_PORTD       RST_CLK_PER2_CLOCK_PCLK_EN_PORTD_Msk




#define RST_CLK_HS_CONTROL_HSE_ON_Pos  0
#define RST_CLK_HS_CONTROL_HSE_ON_Msk  (0x1UL << RST_CLK_HS_CONTROL_HSE_ON_Pos)
#define RST_CLK_HS_CONTROL_HSE_ON      RST_CLK_HS_CONTROL_HSE_ON_Msk

#define RST_CLK_HS_CONTROL_HSE_BYP_Pos 1
#define RST_CLK_HS_CONTROL_HSE_BYP_Msk (0x1UL << RST_CLK_HS_CONTROL_HSE_BYP_Pos)
#define RST_CLK_HS_CONTROL_HSE_BYP     RST_CLK_HS_CONTROL_HSE_BYP_Msk



#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos       0
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_Msk       (0x3UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI       (0x0UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI_DIV_2 (0x1UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE       (0x2UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE_DIV_2 (0x3UL << RST_CLK_CPU_CLOCK_CPU_C1_SEL_Pos)

#define RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos       2
#define RST_CLK_CPU_CLOCK_CPU_C2_SEL_Msk       (0x1UL << RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos)
#define RST_CLK_CPU_CLOCK_CPU_C2_SEL           RST_CLK_CPU_CLOCK_CPU_C2_SEL_Msk

#define RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos       4
#define RST_CLK_CPU_CLOCK_CPU_C3_SEL_Msk       (0xFUL << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos)

#define RST_CLK_CPU_CLOCK_HCLK_SEL_Pos         8
#define RST_CLK_CPU_CLOCK_HCLK_SEL_Msk         (0x3UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_HSI         (0x0UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_CPU_C3      (0x1UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_LSE         (0x2UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)
#define RST_CLK_CPU_CLOCK_HCLK_SEL_LSI         (0x3UL << RST_CLK_CPU_CLOCK_HCLK_SEL_Pos)



#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos        0
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_Msk        (0x3UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSI        (0x0UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSI_DIV_2  (0x1UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSE        (0x2UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C1_SEL_LSE_DIV_2  (0x3UL << RST_CLK_PER1_CLOCK_PER1_C1_SEL_Pos)

#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos        2
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_Msk        (0x3UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_CPU_C1     (0x0UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_PER1_C1    (0x1UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_PLLCPU     (0x2UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_PER1_C2_SEL_HSI_C1_CLK (0x3UL << RST_CLK_PER1_CLOCK_PER1_C2_SEL_Pos)

#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Pos     4
#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Msk     (0x1UL << RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Pos)
#define RST_CLK_PER1_CLOCK_KEY_RESET_PROG         RST_CLK_PER1_CLOCK_KEY_RESET_PROG_Msk

#define RST_CLK_PER1_CLOCK_DMA_EN_Pos             5
#define RST_CLK_PER1_CLOCK_DMA_EN_Msk             (0x1UL << RST_CLK_PER1_CLOCK_DMA_EN_Pos)
#define RST_CLK_PER1_CLOCK_DMA_EN                 RST_CLK_PER1_CLOCK_DMA_EN_Msk

#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos         6
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_Msk         (0x3UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSI         (0x0UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSI_DIV_2   (0x1UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSE         (0x2UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C1_SEL_LSE_DIV_2   (0x3UL << RST_CLK_PER1_CLOCK_WDG_C1_SEL_Pos)

#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos         8
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_Msk         (0x3UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_CPU_C1      (0x0UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_PER1_C1     (0x1UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_PLLCPU      (0x2UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)
#define RST_CLK_PER1_CLOCK_WDG_C2_SEL_HSI_C1_CLK  (0x3UL << RST_CLK_PER1_CLOCK_WDG_C2_SEL_Pos)

#define RST_CLK_PER1_CLOCK_WDG_BRG_Pos            10
#define RST_CLK_PER1_CLOCK_WDG_BRG_Msk            (0x7UL << RST_CLK_PER1_CLOCK_WDG_BRG_Pos)

#define RST_CLK_PER1_CLOCK_WDG_CLK_EN_Pos         13
#define RST_CLK_PER1_CLOCK_WDG_CLK_EN_Msk         (0x1UL << RST_CLK_PER1_CLOCK_WDG_CLK_EN_Pos)
#define RST_CLK_PER1_CLOCK_WDG_CLK_EN             RST_CLK_PER1_CLOCK_WDG_CLK_EN_Msk




/**
 * @brief RST_CLK CPU_PLL clock source selection constants.
 */
typedef enum {
    RST_CLK_PLLCPU_CLK_SRC_HSE    = ((uint32_t)0),
    RST_CLK_PLLCPU_CLK_SRC_CPU_C1 = ((uint32_t)RST_CLK_PLL_CONTROL_PLL_CPU_SEL)
} RST_CLK_PLLCPU_ClockSource_TypeDef;


/**
 * @brief RST_CLK CPU_C1 clock source selection constants.
 */
typedef enum {
    RST_CLK_CPU_C1_CLK_SRC_HSI       = ((uint32_t)RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI),       /*!< HSI as the CPU_C1 source. */
    RST_CLK_CPU_C1_CLK_SRC_HSI_DIV_2 = ((uint32_t)RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSI_DIV_2), /*!< HSI/2 as the CPU_C1 source. */
    RST_CLK_CPU_C1_CLK_SRC_HSE       = ((uint32_t)RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE),       /*!< HSE as the CPU_C1 source. */
    RST_CLK_CPU_C1_CLK_SRC_HSE_DIV_2 = ((uint32_t)RST_CLK_CPU_CLOCK_CPU_C1_SEL_HSE_DIV_2)  /*!< HSE/2 as the CPU_C1 source. */
} RST_CLK_CPU_C1_ClockSource_TypeDef;

/**
 * @brief RST_CLK PLL_CPU_MUL multiplier constants.
 */
typedef enum {
    RST_CLK_PLLCPU_MUL_1 = ((uint32_t)0x0),
    RST_CLK_PLLCPU_MUL_2 = ((uint32_t)0x1),
    RST_CLK_PLLCPU_MUL_3 = ((uint32_t)0x2),
    RST_CLK_PLLCPU_MUL_4 = ((uint32_t)0x3),
    RST_CLK_PLLCPU_MUL_5 = ((uint32_t)0x4),
    RST_CLK_PLLCPU_MUL_6 = ((uint32_t)0x5),
    RST_CLK_PLLCPU_MUL_7 = ((uint32_t)0x6),
    RST_CLK_PLLCPU_MUL_8 = ((uint32_t)0x7)
} RST_CLK_PLLCPU_Multiplier_TypeDef;

/**
 * @brief RST_CLK CPU_C2 clock source selection constants.
 */
typedef enum {
    RST_CLK_CPU_C2_CLK_SRC_CPU_C1 = (((uint32_t)0x0) << RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos), /*!< CPU_C1 as CPU_C2 source. */
    RST_CLK_CPU_C2_CLK_SRC_PLLCPU = (((uint32_t)0x1) << RST_CLK_CPU_CLOCK_CPU_C2_SEL_Pos)  /*!< CPU_PLL as CPU_C2 source. */
} RST_CLK_CPU_C2_ClockSource_TypeDef;

/**
 * @brief RST_CLK CPU_C3 divider constants.
 */
typedef enum {
    RST_CLK_CPU_C3_PRESCALER_DIV_1   = (((uint32_t)0x0) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_2   = (((uint32_t)0x8) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_4   = (((uint32_t)0x9) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_8   = (((uint32_t)0xA) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_16  = (((uint32_t)0xB) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_32  = (((uint32_t)0xC) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_64  = (((uint32_t)0xD) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_128 = (((uint32_t)0xE) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos),
    RST_CLK_CPU_C3_PRESCALER_DIV_256 = (((uint32_t)0xF) << RST_CLK_CPU_CLOCK_CPU_C3_SEL_Pos)
} RST_CLK_CPU_C3_Prescaler_TypeDef;

/**
 * @brief RST_CLK HCLK clock source selection constants.
 */
typedef enum {
    RST_CLK_CPU_HCLK_CLK_SRC_HSI    = ((uint32_t)RST_CLK_CPU_CLOCK_HCLK_SEL_HSI),
    RST_CLK_CPU_HCLK_CLK_SRC_CPU_C3 = ((uint32_t)RST_CLK_CPU_CLOCK_HCLK_SEL_CPU_C3),
    RST_CLK_CPU_HCLK_CLK_SRC_LSE    = ((uint32_t)RST_CLK_CPU_CLOCK_HCLK_SEL_LSE),
    RST_CLK_CPU_HCLK_CLK_SRC_LSI    = ((uint32_t)RST_CLK_CPU_CLOCK_HCLK_SEL_LSI)
} RST_CLK_HCLK_ClockSource_TypeDef;

                                           /**
 * @brief RST_CLK flag identifiers.
 */
typedef enum {
    RST_CLK_FLAG_HSERDY    = RST_CLK_CLOCK_STATUS_HSE_RDY,
    RST_CLK_FLAG_PLLCPURDY = RST_CLK_CLOCK_STATUS_PLL_CPU_RDY
} RST_CLK_Flags_TypeDef;


/**
 * @brief RST_CLK HCLK clock init struct definition.
 */
typedef struct {
    RST_CLK_CPU_C1_ClockSource_TypeDef RST_CLK_CPU_C1_Source;      /*!< CPU_C1 clock source selection.
                                                                        Not used if (RSC_CLK_PLLCPU_ClockSource == RST_CLK_PLLCPU_CLK_SRC_HSE)).
                                                                        This parameter can be a value of the @ref RST_CLK_CPU_C1_ClockSource_TypeDef. */
    RST_CLK_PLLCPU_ClockSource_TypeDef RST_CLK_PLLCPU_ClockSource; /*!< CPU_PLL clock source selection.
                                                                        Not used if (RST_CLK_CPU_C2_ClockSource == RST_CLK_CPU_C2_CLK_SRC_CPU_C1).
                                                                        This parameter can be a value of the @ref RST_CLK_PLLCPU_ClockSource_TypeDef. */
    RST_CLK_PLLCPU_Multiplier_TypeDef RST_CLK_PLLCPU_Multiplier;   /*!< CPU_PLL clock multiplier selection.
                                                                        Not used if (RST_CLK_CPU_C2_ClockSource == RST_CLK_CPU_C2_CLK_SRC_CPU_C1).
                                                                        This parameter can be a value of the @ref RST_CLK_PLLCPU_Multiplier_TypeDef. */
    RST_CLK_CPU_C2_ClockSource_TypeDef RST_CLK_CPU_C2_ClockSource; /*!< CPU_C2 clock source selection.
                                                                        This parameter can be a value of the @ref RST_CLK_CPU_C2_ClockSource_TypeDef. */
    RST_CLK_CPU_C3_Prescaler_TypeDef RST_CLK_CPU_C3_Prescaler;     /*!< CPU_C3 clock divider.
                                                                        This parameter can be a value of the @ref RST_CLK_CPU_C3_Prescaler_TypeDef. */
    RST_CLK_HCLK_ClockSource_TypeDef RST_CLK_HCLK_ClockSource;     /*!< HCLK clock source selection.
                                                                        All other fields are not used if (RST_CLK_HCLK_ClockSource != RST_CLK_CPU_HCLK_CLK_SRC_CPU_C3).
                                                                        This parameter can be a value of the @ref RST_CLK_HCLK_ClockSource_TypeDef. */
} RST_CLK_HCLK_InitTypeDef;

void RST_CLK_DeInit(void);

int RST_CLK_HCLK_Init(const RST_CLK_HCLK_InitTypeDef* RST_CLK_HCLK_InitStruct);

void RST_CLK_HSE_Cmd(int NewState);

int  RST_CLK_HSE_GetStatus(void);

void RST_CLK_CPU_PLL_Config(RST_CLK_PLLCPU_ClockSource_TypeDef PLLCPU_Source, uint32_t PLLCPU_Multiplier);
void RST_CLK_CPU_PLL_Cmd(int NewState);
int  RST_CLK_CPU_PLL_GetCmdState(void);
int  RST_CLK_CPU_PLL_GetStatus(void);

void RST_CLK_CPU_C1_ClkSelection(RST_CLK_CPU_C1_ClockSource_TypeDef CPU_C1_Source);
void RST_CLK_CPU_C2_ClkSelection(RST_CLK_CPU_C2_ClockSource_TypeDef CPU_C2_Source);
void RST_CLK_CPU_C3_SetPrescaler(RST_CLK_CPU_C3_Prescaler_TypeDef CPU_CLK_DivValue);
void RST_CLK_HCLK_ClkSelection(RST_CLK_HCLK_ClockSource_TypeDef CPU_HCLK_Source);


int RST_CLK_GetFlagStatus(RST_CLK_Flags_TypeDef RST_CLK_Flag);


#endif /* MDR1206FI_RST_CLK_H */
