$_MODS += box_around_test

$_SRCS-box_around_test += box_around.c

$_DEPS-box_around_test += $(PLATFORM).driver.sonar_sensor
$_DEPS-box_around_test += $(PLATFORM).driver.nxt_motor
$_DEPS-box_around_test += $(PLATFORM).driver.nxt_avr_init
