
$_CPPFLAGS += -I$($PLATFORM)/include
$_MODS += box_around_test
$_SRCS-box_around_test += box_around.c
$_DEPS-box_around_test += $(PLATFORM).driver.sonar_sensor $(PLATFORM).driver.nxt_motor $(PLATFORM).driver.nxt_avr_init embox.driver.pins
