
TARGET = embox

PLATFORM=niiet_k1921vg1t_dev

CHIP_VENDOR = niiet
PLATFORM_VENDOR = niiet

ARCH = riscv

CROSS_COMPILE = riscv64-unknown-elf-

CFLAGS += -g3 -O0

CFLAGS += -march=rv32imfc_zicsr_zifencei -mabi=ilp32f

LDFLAGS += -melf32lriscv
