/**
 * \file on_boot_express_tests.h
 * \date Nov 17, 2009
 * \author afomin
 * \details
 */

#ifndef ON_BOOT_EXPRESS_TESTS_H_
#define ON_BOOT_EXPRESS_TESTS_H_

#define TEST_CHECKSUM_ON_BOOT_ENABLE TRUE
#define TEST_CPU_CONTEXT_ON_BOOT_ENABLE TRUE
#define TEST_FORCE_IRQ_ON_BOOT_ENABLE TRUE
#define TEST_LOCAL_IRQ_SAVE_ON_BOOT_ENABLE TRUE
#define TEST_MMU_ON_BOOT_ENABLE TRUE
#define TEST_RECURSION_ON_BOOT_ENABLE TRUE
#define TEST_SOFT_TRAPS_ON_BOOT_ENABLE TRUE
#define TEST_TIMER_CALLBACK_ON_BOOT_ENABLE TRUE

#endif /* ON_BOOT_EXPRESS_TESTS_H_ */
