$_APIS += kmalloc

$_MODS              += slob
$_SRCS-slob         += slob.c
$_PROVIDES-slob     += kmalloc

$_MODS              += slab_fit
$_SRCS-slab_fit     += slab_fit.c
$_DEPS-slab_fit     += slab
$_PROVIDES-slab_fit += kmalloc

