
$_MODS += terminal

$_SRCS-terminal += vtparse_table.c
$_SRCS-terminal += vtparse.c
$_SRCS-terminal += vtbuild.c
$_SRCS-terminal += terminal.c


ifdef CONFIG_DRIVER_SUBSYSTEM
$_MODS += zero
$_SRCS-zero += zero.c
$_DEPS-zero += core.kernel.drv_subsys
endif

