$_MODS += nxt_bluetooth btm_bluetooth
$_SRCS-nxt_bluetooth += nxt_bluetooth_usart.c nxt_bluetooth_assist.c
$_DEPS-nxt_bluetooth += embox.driver.pins

$_SRCS-btm_bluetooth += btm_bluetooth.c
$_DEPS-btm_bluetooth += embox.driver.pins
