
$_PACKAGE := embox.cmd.tty

$_MODS += serial_screens
$_SRCS-serial_screens += serial.c
$_DEPS-serial_screens += embox.driver.tty_ng.core
$_REQUIRES-serial_screens += embox.hal.serial embox.cmd.sh.shell_api
