$_CPPFLAGS += -I$(SRC_DIR)/include/posix

$_PACKAGE := embox.prom

$_APIS += printf

$_MODS += prom_printf
$_SRCS-prom_printf += prom_printf.[c|h]
$_PROVIDES-prom_printf  += embox.prom.printf

$_MODS += noprom_printf
$_SRCS-noprom_printf += noprom_printf.h
$_PROVIDES-noprom_printf  += embox.prom.printf



