$_PACKAGE = embox.example.tty

$_MODS           += kbd_example
$_SRCS-kbd_example = kbd.c
$_DEPS-kbd_example += embox.driver.tty_posix

$_MODS           += screen_example
$_SRCS-screen_example = screen.c
$_DEPS-screen_example += embox.driver.tty_posix
