/*
 * mem_help.inc
 *
 *  Created on: 24.02.2009
 *      Author: Alexey Fomin
 */

"*** WMEM\n"
" - writes to memory\n"
"* FORMAT: wmem [-h] -a <addr> -v <value>\n"
"\t -h ------ to see this page\n"
"\t <addr> -- address where to write\n"
"\t <value> - value that will be written\n"
"\t				two last bits must be zero\n"
"Data format (for <value> and <address>):\n"
"\t 0x1111 - in hex\n"
"\t   1111 - in decimal"

