OBJS-y                    += string.o
OBJS-$(MONITOR_MISC)      += misc.o
OBJS-$(MONITOR_NETWORK)	  += crc32.o
OBJS-$(MONITOR_NETWORK)   += md5.o
OBJS-$(MONITOR_NETWORK)   += ipaux.o

include $(SRC_DIR)/common.mk
