$_MODS         += nxt_lcd
$_SRCS-nxt_lcd += nxt_lcd.c
$_SRCS-nxt_lcd += display.c

$_MODS                  += nxt_diag_lcd
$_SRCS-nxt_diag_lcd     += diag.c
$_DEPS-nxt_diag_lcd     += $(PLATFORM).driver.nxt_lcd
$_PROVIDES-nxt_diag_lcd += embox.hal.diag
