
$_CPPFLAGS += -I$($PLATFORM)/include
$_MODS += wake_up_test
$_SRCS-wake_up_test += wake_up.c
$_DEPS-wake_up_test += $(PLATFORM).driver.nxt_motor $(PLATFORM).driver.nxt_avr_init $(PLATFORM).driver.soft_i2c embox.driver.pins
