ifdef CONFIG_THREAD
$_PACKAGE := core.kernel.threads

$_MODS += core

$_DEPS-core += scheduler synchronization
$_DEPS-core += embox.hal.context

$_SRCS-core += thread.c
$_SRCS-core += thread_heap.c
endif
