$_PACKAGE = embox.test.util

$_MODS           += array_test
$_SRCS-array_test = array_test.c

$_MODS           += list_test
$_SRCS-list_test  = list_test.c

$_MODS           += slist_test
$_SRCS-slist_test = slist_test.c

$_MODS           += pool_test
$_SRCS-pool_test  = pool_test.c
