include $(SCRIPTS_DIR)/autoconf

OBJS-$(MONITOR_NET_ARP)              += arp.o
OBJS-$(MONITOR_NET_IP_V4)            += ip_v4.o
OBJS-$(MONITOR_NET_ICMP)             += icmp.o
OBJS-$(MONITOR_NET_UDP)              += udp.o
OBJS-$(MONITOR_NET_TFTP)             += tftp.o
OBJS-$(MONITOR_NET_DHCP)             += dhcp.o

include $(SRC_DIR)/common.mk
